(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa="INPUT",ba="Symbol.iterator",ca="_imgFileNameError",da="_imgUrlTextError",ea="allHolder",fa="aria-expanded",ha="bgresponse",ia="commentBodyField",e="complete",ja="displayModeLayout",ka="displayModeNone",l="div",la="encodedSelectedId",ma="es3",p="function",na="goog-zippy-collapsed",oa="goog-zippy-expanded",qa="hidden",ra="identity-type-",sa="identityHolder",ta="identityMenu",ua="keypress",va="layout-widget-description",wa="layout-widget-title",xa="main-status-holder",ya="nameUrlIdentityHolder",
q="none",za="number",r="object",Aa="postCommentSubmit",Ba="ready",Ca="rotate(-45deg)",Da="sectionWidth",Ea="select-multiple",Fa="showPreview",Ga="status-message-inner",u="string",Ha="subscribeButtonHolder",Ia="success",v,Ja=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},Ka=typeof Object.defineProperties==p?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},La=function(a){a=[r==typeof globalThis&&
globalThis,a,r==typeof window&&window,r==typeof self&&self,r==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},Ma=La(this),Na=function(a,b){if(b)a:{var c=Ma;a=a.split(".");for(var d=0;d<a.length-1;d++){var f=a[d];if(!(f in c))break a;c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&Ka(c,a,{configurable:!0,writable:!0,value:b})}};
Na("Symbol",function(a){if(a)return a;var b=function(g,k){this.hf=g;Ka(this,"description",{configurable:!0,writable:!0,value:k})};b.prototype.toString=function(){return this.hf};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,f=function(g){if(this instanceof f)throw new TypeError("Symbol is not a constructor");return new b(c+(g||"")+"_"+d++,g)};return f},"es6",ma);
Na(ba,function(a){if(a)return a;a=Symbol(ba);for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=Ma[b[c]];typeof d===p&&typeof d.prototype[a]!=p&&Ka(d.prototype,a,{configurable:!0,writable:!0,value:function(){return Oa(Ja(this))}})}return a},"es6",ma);
var Oa=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},Pa=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:Ja(a)}},Qa=typeof Object.create==p?Object.create:function(a){var b=function(){};b.prototype=a;return new b},Ra;
if(typeof Object.setPrototypeOf==p)Ra=Object.setPrototypeOf;else{var Sa;a:{var Ta={a:!0},Ua={};try{Ua.__proto__=Ta;Sa=Ua.a;break a}catch(a){}Sa=!1}Ra=Sa?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var Va=Ra,Wa=function(a,b){a.prototype=Qa(b.prototype);a.prototype.constructor=a;if(Va)Va(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.u=b.prototype},Xa=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
Na("WeakMap",function(a){function b(){}function c(m){var n=typeof m;return n===r&&null!==m||n===p}function d(m){if(!Xa(m,g)){var n=new b;Ka(m,g,{value:n})}}function f(m){var n=Object[m];n&&(Object[m]=function(t){if(t instanceof b)return t;Object.isExtensible(t)&&d(t);return n(t)})}if(function(){if(!a||!Object.seal)return!1;try{var m=Object.seal({}),n=Object.seal({}),t=new a([[m,2],[n,3]]);if(2!=t.get(m)||3!=t.get(n))return!1;t.delete(m);t.set(n,4);return!t.has(m)&&4==t.get(n)}catch(W){return!1}}())return a;
var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var k=0,h=function(m){this.R=(k+=Math.random()+1).toString();if(m){m=Pa(m);for(var n;!(n=m.next()).done;)n=n.value,this.set(n[0],n[1])}};h.prototype.set=function(m,n){if(!c(m))throw Error("Invalid WeakMap key");d(m);if(!Xa(m,g))throw Error("WeakMap key fail: "+m);m[g][this.R]=n;return this};h.prototype.get=function(m){return c(m)&&Xa(m,g)?m[g][this.R]:void 0};h.prototype.has=function(m){return c(m)&&Xa(m,g)&&Xa(m[g],
this.R)};h.prototype.delete=function(m){return c(m)&&Xa(m,g)&&Xa(m[g],this.R)?delete m[g][this.R]:!1};return h},"es6",ma);
Na("Map",function(a){if(function(){if(!a||typeof a!=p||!a.prototype.entries||typeof Object.seal!=p)return!1;try{var h=Object.seal({x:4}),m=new a(Pa([[h,"s"]]));if("s"!=m.get(h)||1!=m.size||m.get({x:4})||m.set({x:4},"t")!=m||2!=m.size)return!1;var n=m.entries(),t=n.next();if(t.done||t.value[0]!=h||"s"!=t.value[1])return!1;t=n.next();return t.done||4!=t.value[0].x||"t"!=t.value[1]||!n.next().done?!1:!0}catch(W){return!1}}())return a;var b=new WeakMap,c=function(h){this.Xa={};this.ea=g();this.size=0;
if(h){h=Pa(h);for(var m;!(m=h.next()).done;)m=m.value,this.set(m[0],m[1])}};c.prototype.set=function(h,m){h=0===h?0:h;var n=d(this,h);n.list||(n.list=this.Xa[n.id]=[]);n.C?n.C.value=m:(n.C={next:this.ea,fa:this.ea.fa,head:this.ea,key:h,value:m},n.list.push(n.C),this.ea.fa.next=n.C,this.ea.fa=n.C,this.size++);return this};c.prototype.delete=function(h){h=d(this,h);return h.C&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.Xa[h.id],h.C.fa.next=h.C.next,h.C.next.fa=h.C.fa,h.C.head=null,
this.size--,!0):!1};c.prototype.clear=function(){this.Xa={};this.ea=this.ea.fa=g();this.size=0};c.prototype.has=function(h){return!!d(this,h).C};c.prototype.get=function(h){return(h=d(this,h).C)&&h.value};c.prototype.entries=function(){return f(this,function(h){return[h.key,h.value]})};c.prototype.keys=function(){return f(this,function(h){return h.key})};c.prototype.values=function(){return f(this,function(h){return h.value})};c.prototype.forEach=function(h,m){for(var n=this.entries(),t;!(t=n.next()).done;)t=
t.value,h.call(m,t[1],t[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(h,m){var n=m&&typeof m;n==r||n==p?b.has(m)?n=b.get(m):(n=""+ ++k,b.set(m,n)):n="p_"+m;var t=h.Xa[n];if(t&&Xa(h.Xa,n))for(h=0;h<t.length;h++){var W=t[h];if(m!==m&&W.key!==W.key||m===W.key)return{id:n,list:t,index:h,C:W}}return{id:n,list:t,index:-1,C:void 0}},f=function(h,m){var n=h.ea;return Oa(function(){if(n){for(;n.head!=h.ea;)n=n.fa;for(;n.next!=n.head;)return n=n.next,{done:!1,value:m(n)};n=null}return{done:!0,
value:void 0}})},g=function(){var h={};return h.fa=h.next=h.head=h},k=0;return c},"es6",ma);Na("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var f=d.length,g=0;g<f;g++){var k=d[g];if(b.call(c,k,g,d)){b=k;break a}}b=void 0}return b}},"es6",ma);
var Ya=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,f={next:function(){if(!d&&c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}d=!0;return{done:!0,value:void 0}}};f[Symbol.iterator]=function(){return f};return f};Na("Array.prototype.values",function(a){return a?a:function(){return Ya(this,function(b,c){return c})}},"es8",ma);Na("Array.prototype.keys",function(a){return a?a:function(){return Ya(this,function(b){return b})}},"es6",ma);
Na("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var f=[],g="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if(typeof g==p){b=g.call(b);for(var k=0;!(g=b.next()).done;)f.push(c.call(d,g.value,k++))}else for(g=b.length,k=0;k<g;k++)f.push(c.call(d,b[k],k));return f}},"es6",ma);
var Za=Za||{},w=this||self,$a=function(){},ab=function(a){a.Bc=void 0;a.mg=function(){return a.Bc?a.Bc:a.Bc=new a}},bb=function(a){var b=typeof a;b=b!=r?b:a?Array.isArray(a)?"array":b:"null";return"array"==b||b==r&&typeof a.length==za},cb=function(a){var b=typeof a;return b==r&&null!=a||b==p},fb=function(a){return Object.prototype.hasOwnProperty.call(a,db)&&a[db]||(a[db]=++eb)},db="closure_uid_"+(1E9*Math.random()>>>0),eb=0,gb=function(a,b,c){return a.call.apply(a.bind,arguments)},hb=function(a,b,
c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var f=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(f,d);return a.apply(b,f)}}return function(){return a.apply(b,arguments)}},x=function(a,b,c){x=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?gb:hb;return x.apply(null,arguments)},y=function(a,b,c){a=a.split(".");c=c||w;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+
a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}:c[d]=b},z=function(a,b){function c(){}c.prototype=b.prototype;a.u=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Uh=function(d,f,g){for(var k=Array(arguments.length-2),h=2;h<arguments.length;h++)k[h-2]=arguments[h];return b.prototype[f].apply(d,k)}},jb=function(a){return a};function kb(a){if(Error.captureStackTrace)Error.captureStackTrace(this,kb);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}z(kb,Error);kb.prototype.name="CustomError";var lb;var mb=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,f=0;f<d;f++)c+=a[f]+(f<b.length?b[f]:"%s");kb.call(this,c+a[d])};z(mb,kb);mb.prototype.name="AssertionError";var nb=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(typeof a===u)return typeof b!==u||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ob=Array.prototype.lastIndexOf?function(a,b,c){return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(typeof a===u)return typeof b!==u||1!=b.length?
-1:a.lastIndexOf(b,c);for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1},pb=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=typeof a===u?a.split(""):a,g=0;g<d;g++)g in f&&b.call(c,f[g],g,a)},qb=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=typeof a===u?a.split(""):a,g=0;g<d;g++)if(g in f&&b.call(c,f[g],g,a))return!0;return!1};function A(a,b){return 0<=nb(a,b)}
function rb(a){if(!Array.isArray(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0}function sb(a,b){b=nb(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c}function tb(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var ub=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},vb=function(a,b){return a<b?-1:a>b?1:0};function wb(){var a=w.navigator;return a&&(a=a.userAgent)?a:""}function B(a){return-1!=wb().indexOf(a)};var xb=function(a){xb[" "](a);return a};xb[" "]=$a;var yb=function(a,b,c,d){d=d?d(b):b;return Object.prototype.hasOwnProperty.call(a,d)?a[d]:a[d]=c(b)};var zb=B("Opera"),D=B("Trident")||B("MSIE"),Ab=B("Edge"),E=B("Gecko")&&!(-1!=wb().toLowerCase().indexOf("webkit")&&!B("Edge"))&&!(B("Trident")||B("MSIE"))&&!B("Edge"),F=-1!=wb().toLowerCase().indexOf("webkit")&&!B("Edge"),Bb=B("Macintosh"),Cb;
a:{var Db="",Eb=function(){var a=wb();if(E)return/rv:([^\);]+)(\)|;)/.exec(a);if(Ab)return/Edge\/([\d\.]+)/.exec(a);if(D)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(F)return/WebKit\/(\S+)/.exec(a);if(zb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Eb&&(Db=Eb?Eb[1]:"");if(D){var Fb,Gb=w.document;Fb=Gb?Gb.documentMode:void 0;if(null!=Fb&&Fb>parseFloat(Db)){Cb=String(Fb);break a}}Cb=Db}
var Hb=Cb,Ib={},Jb=function(a){return yb(Ib,a,function(){for(var b=0,c=ub(String(Hb)).split("."),d=ub(String(a)).split("."),f=Math.max(c.length,d.length),g=0;0==b&&g<f;g++){var k=c[g]||"",h=d[g]||"";do{k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==k[0].length&&0==h[0].length)break;b=vb(0==k[1].length?0:parseInt(k[1],10),0==h[1].length?0:parseInt(h[1],10))||vb(0==k[2].length,0==h[2].length)||vb(k[2],h[2]);k=k[3];h=h[3]}while(0==b)}return 0<=b})};var Kb=function(a){return a};function Lb(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Nb(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return!0;return!1}function Ob(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function Pb(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function Qb(a,b){for(var c in a)if(a[c]==b)return!0;return!1}function Rb(a){for(var b in a)return!1;return!0}var Sb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
function Tb(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var g=0;g<Sb.length;g++)c=Sb[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var Ub,Vb=function(){if(void 0===Ub){var a=null,b=w.trustedTypes;if(b&&b.createPolicy)try{a=b.createPolicy("goog#html",{createHTML:jb,createScript:jb,createScriptURL:jb})}catch(c){w.console&&w.console.error(c.message)}Ub=a}return Ub};var Yb=function(a,b){this.af=a===Wb&&b||"";this.Cf=Xb};Yb.prototype.xa=!0;Yb.prototype.na=function(){return this.af};var Xb={},Wb={};var $b=function(a,b){this.Xc=b===Zb?a:""};$b.prototype.xa=!0;$b.prototype.na=function(){return this.Xc.toString()};$b.prototype.toString=function(){return this.Xc+""};var Zb={};var I=function(a,b){this.Wc=b===ac?a:""};I.prototype.xa=!0;I.prototype.na=function(){return this.Wc.toString()};I.prototype.toString=function(){return this.Wc.toString()};
var bc=RegExp('^(?:audio/(?:3gpp2|3gpp|aac|L16|midi|mp3|mp4|mpeg|oga|ogg|opus|x-m4a|x-matroska|x-wav|wav|webm)|font/\\w+|image/(?:bmp|gif|jpeg|jpg|png|tiff|webp|x-icon)|video/(?:mpeg|mp4|ogg|webm|quicktime|x-matroska))(?:;\\w+=(?:\\w+|"[\\w;,= ]+"))*$',"i"),cc=/^data:(.*);base64,[a-z0-9+\/]+=*$/i,dc=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,ec=function(a){if(a instanceof I)return a;a=typeof a==r&&a.xa?a.na():String(a);if(dc.test(a))a=new I(a,ac);else{a=String(a);a=a.replace(/(%0A|%0D)/g,
"");var b=a.match(cc);a=b&&bc.test(b[1])?new I(a,ac):null}return a},ac={},fc=new I("about:invalid#zClosurez",ac);var gc={},hc=function(a,b){this.Vc=b===gc?a:"";this.xa=!0};hc.prototype.na=function(){return this.Vc};hc.prototype.toString=function(){return this.Vc.toString()};var ic=new hc("",gc);
function jc(a){if(a instanceof I)return'url("'+(a instanceof I&&a.constructor===I?a.Wc:"type_error:SafeUrl").replace(/</g,"%3c").replace(/[\\"]/g,"\\$&")+'")';if(a instanceof Yb)a=a instanceof Yb&&a.constructor===Yb&&a.Cf===Xb?a.af:"type_error:Const";else{a=String(a);var b=a.replace(kc,"$1").replace(kc,"$1").replace(lc,"url");if(mc.test(b)){if(b=!nc.test(a)){for(var c=b=!0,d=0;d<a.length;d++){var f=a.charAt(d);"'"==f&&c?b=!b:'"'==f&&b&&(c=!c)}b=b&&c&&oc(a)}a=b?pc(a):"zClosurez"}else a="zClosurez"}if(/[{;}]/.test(a))throw new mb("Value does not allow [{;}], got: %s.",
[a]);return a}function oc(a){for(var b=!0,c=/^[-_a-zA-Z0-9]$/,d=0;d<a.length;d++){var f=a.charAt(d);if("]"==f){if(b)return!1;b=!0}else if("["==f){if(!b)return!1;b=!1}else if(!b&&!c.test(f))return!1}return b}
var mc=RegExp("^[-,.\"'%_!#/ a-zA-Z0-9\\[\\]]+$"),lc=RegExp("\\b(url\\([ \t\n]*)('[ -&(-\\[\\]-~]*'|\"[ !#-\\[\\]-~]*\"|[!#-&*-\\[\\]-~]*)([ \t\n]*\\))","g"),kc=RegExp("\\b(calc|cubic-bezier|fit-content|hsl|hsla|linear-gradient|matrix|minmax|repeat|rgb|rgba|(rotate|scale|translate)(X|Y|Z|3d)?|var)\\([-+*/0-9a-zA-Z.%#\\[\\], ]+\\)","g"),nc=/\/\*/;
function pc(a){return a.replace(lc,function(b,c,d,f){var g="";d=d.replace(/^(['"])(.*)\1$/,function(k,h,m){g=h;return m});b=(ec(d)||fc).na();return c+g+b+g+f})};var qc={},rc=function(a,b){this.Uc=b===qc?a:"";this.xa=!0},sc=function(a,b){if(-1!=a.indexOf("<"))throw Error("Selector does not allow '<', got: "+a);var c=a.replace(/('|")((?!\1)[^\r\n\f\\]|\\[\s\S])*\1/g,"");if(!/^[-_a-zA-Z0-9#.:* ,>+~[\]()=^$|]+$/.test(c))throw Error("Selector allows only [-_a-zA-Z0-9#.:* ,>+~[\\]()=^$|] and strings, got: "+a);a:{for(var d={"(":")","[":"]"},f=[],g=0;g<c.length;g++){var k=c[g];if(d[k])f.push(d[k]);else if(Qb(d,k)&&f.pop()!=k){c=!1;break a}}c=0==f.length}if(!c)throw Error("() and [] in selector must be balanced, got: "+
a);if(!(b instanceof hc)){c="";for(var h in b)if(Object.prototype.hasOwnProperty.call(b,h)){if(!/^[-_a-zA-Z0-9]+$/.test(h))throw Error("Name allows only [-_a-zA-Z0-9], got: "+h);d=b[h];null!=d&&(d=Array.isArray(d)?d.map(jc).join(" "):jc(d),c+=h+":"+d+";")}b=c?new hc(c,gc):ic}a=a+"{"+(b instanceof hc&&b.constructor===hc?b.Vc:"type_error:SafeStyle").replace(/</g,"\\3C ")+"}";return new rc(a,qc)},uc=function(a){var b="",c=function(d){Array.isArray(d)?d.forEach(c):b+=tc(d)};Array.prototype.forEach.call(arguments,
c);return new rc(b,qc)};rc.prototype.na=function(){return this.Uc};var tc=function(a){return a instanceof rc&&a.constructor===rc?a.Uc:"type_error:SafeStyleSheet"};rc.prototype.toString=function(){return this.Uc.toString()};var vc={},wc=function(a,b,c){this.Tc=c===vc?a:"";this.xa=!0};wc.prototype.na=function(){return this.Tc.toString()};wc.prototype.toString=function(){return this.Tc.toString()};var xc=/^[\w+/_-]+[=]{0,2}$/,yc=function(a,b){b=(b||w).document;return b.querySelector?(a=b.querySelector(a))&&(a=a.nonce||a.getAttribute("nonce"))&&xc.test(a)?a:"":""};var zc=function(a,b){this.width=a;this.height=b};v=zc.prototype;v.clone=function(){return new zc(this.width,this.height)};v.Tf=function(){return this.width*this.height};v.aspectRatio=function(){return this.width/this.height};v.isEmpty=function(){return!this.Tf()};v.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};v.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
v.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};v.scale=function(a,b){this.width*=a;this.height*=typeof b===za?b:a;return this};var Ac=function(a){return a.replace(/(\r\n|\r|\n)+/g," ")},Bc=function(a){return a.replace(/\xa0|[ \t]+/g," ")};var Ec=function(a){return a?new Cc(Dc(a)):lb||(lb=new Cc)},J=function(a){return Fc(document,a)},Fc=function(a,b){return typeof b===u?a.getElementById(b):b},Hc=function(a,b){Lb(b,function(c,d){c&&typeof c==r&&c.xa&&(c=c.na());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Gc.hasOwnProperty(d)?a.setAttribute(Gc[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})},Gc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",
frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},Jc=function(a,b,c){return Ic(document,arguments)},Ic=function(a,b){var c=b[1],d=Kc(a,String(b[0]));c&&(typeof c===u?d.className=c:Array.isArray(c)?d.className=c.join(" "):Hc(d,c));2<b.length&&Lc(a,d,b,2);return d},Lc=function(a,b,c,d){function f(h){h&&b.appendChild(typeof h===u?a.createTextNode(h):h)}for(;d<c.length;d++){var g=c[d];
if(!bb(g)||cb(g)&&0<g.nodeType)f(g);else{a:{if(g&&typeof g.length==za){if(cb(g)){var k=typeof g.item==p||typeof g.item==u;break a}if(typeof g===p){k=typeof g.item==p;break a}}k=!1}pb(k?tb(g):g,f)}}},Kc=function(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)},Mc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)},Dc=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document},Cc=function(a){this.sa=a||w.document||document};v=Cc.prototype;
v.Ia=function(a){return Fc(this.sa,a)};v.$=Cc.prototype.Ia;v.getElementsByTagName=function(a,b){return(b||this.sa).getElementsByTagName(String(a))};
v.$d=function(a,b,c){c=c||this.sa;a=a&&"*"!=a?String(a).toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(a||b))b=c.querySelectorAll(a+(b?"."+b:""));else if(b&&c.getElementsByClassName)if(c=c.getElementsByClassName(b),a){for(var d={},f=0,g=0,k;k=c[g];g++)a==k.nodeName&&(d[f++]=k);d.length=f;b=d}else b=c;else if(c=c.getElementsByTagName(a||"*"),b){d={};for(g=f=0;k=c[g];g++)a=k.className,typeof a.split==p&&A(a.split(/\s+/),b)&&(d[f++]=k);d.length=f;b=d}else b=c;return b};
v.lc=function(a,b,c){return Ic(this.sa,arguments)};v.createElement=function(a){return Kc(this.sa,a)};v.createTextNode=function(a){return this.sa.createTextNode(String(a))};v.appendChild=function(a,b){a.appendChild(b)};v.append=function(a,b){Lc(Dc(a),a,arguments,1)};v.canHaveChildren=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case aa:case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
v.removeNode=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};v.isWindow=function(a){return cb(a)&&a.window==a};v.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};function Nc(a){a&&typeof a.ra==p&&a.ra()};var K=function(){this.Ea=this.Ea;this.Tb=this.Tb};K.prototype.Ea=!1;K.prototype.ra=function(){this.Ea||(this.Ea=!0,this.m())};K.prototype.m=function(){if(this.Tb)for(;this.Tb.length;)this.Tb.shift()()};var L=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.kb=!1};L.prototype.stopPropagation=function(){this.kb=!0};L.prototype.preventDefault=function(){this.defaultPrevented=!0};var Oc=function(){if(!w.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{w.addEventListener("test",$a,b),w.removeEventListener("test",$a,b)}catch(c){}return a}();var N=function(a,b){L.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.Ga=null;a&&this.ne(a,b)};z(N,L);var Pc={2:"touch",3:"pen",4:"mouse"};
N.prototype.ne=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;if(b=a.relatedTarget){if(E){a:{try{xb(b.nodeName);var f=!0;break a}catch(g){}f=!1}f||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=
d.screenY||0):(this.offsetX=F||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=F||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||(c==ua?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||
0;this.pointerType=typeof a.pointerType===u?a.pointerType:Pc[a.pointerType]||"";this.state=a.state;this.Ga=a;a.defaultPrevented&&N.u.preventDefault.call(this)};N.prototype.stopPropagation=function(){N.u.stopPropagation.call(this);this.Ga.stopPropagation?this.Ga.stopPropagation():this.Ga.cancelBubble=!0};N.prototype.preventDefault=function(){N.u.preventDefault.call(this);var a=this.Ga;a.preventDefault?a.preventDefault():a.returnValue=!1};var Qc="closure_listenable_"+(1E6*Math.random()|0),Rc=function(a){return!(!a||!a[Qc])};var Sc=0;var Tc=function(a,b,c,d,f,g){this.listener=a;this.proxy=b;this.src=c;this.type=d;this.capture=!!f;this.Fb=g;this.key=++Sc;this.mb=this.wb=!1};Tc.prototype.Qb=function(){this.mb=!0;this.Fb=this.src=this.proxy=this.listener=null};var Uc=function(a){this.src=a;this.v={};this.qb=0};v=Uc.prototype;v.add=function(a,b,c,d,f){var g=a.toString();a=this.v[g];a||(a=this.v[g]=[],this.qb++);var k=Vc(a,b,d,f);-1<k?(b=a[k],c||(b.wb=!1)):(b=new Tc(b,null,this.src,g,!!d,f),b.wb=c,a.push(b));return b};v.remove=function(a,b,c,d){a=a.toString();if(!(a in this.v))return!1;var f=this.v[a];b=Vc(f,b,c,d);return-1<b?(f[b].Qb(),Array.prototype.splice.call(f,b,1),0==f.length&&(delete this.v[a],this.qb--),!0):!1};
v.Pe=function(a){var b=a.type;if(!(b in this.v))return!1;var c=sb(this.v[b],a);c&&(a.Qb(),0==this.v[b].length&&(delete this.v[b],this.qb--));return c};v.Ub=function(a){a=a&&a.toString();var b=0,c;for(c in this.v)if(!a||c==a){for(var d=this.v[c],f=0;f<d.length;f++)++b,d[f].Qb();delete this.v[c];this.qb--}return b};v.$a=function(a,b,c,d){a=this.v[a.toString()];var f=-1;a&&(f=Vc(a,b,c,d));return-1<f?a[f]:null};
v.hasListener=function(a,b){var c=void 0!==a,d=c?a.toString():"",f=void 0!==b;return Nb(this.v,function(g){for(var k=0;k<g.length;++k)if(!(c&&g[k].type!=d||f&&g[k].capture!=b))return!0;return!1})};var Vc=function(a,b,c,d){for(var f=0;f<a.length;++f){var g=a[f];if(!g.mb&&g.listener==b&&g.capture==!!c&&g.Fb==d)return f}return-1};var Wc="closure_lm_"+(1E6*Math.random()|0),Xc={},Yc=0,O=function(a,b,c,d,f){if(d&&d.once)return Zc(a,b,c,d,f);if(Array.isArray(b)){for(var g=0;g<b.length;g++)O(a,b[g],c,d,f);return null}c=$c(c);return Rc(a)?a.Pa(b,c,cb(d)?!!d.capture:!!d,f):ad(a,b,c,!1,d,f)},ad=function(a,b,c,d,f,g){if(!b)throw Error("Invalid event type");var k=cb(f)?!!f.capture:!!f,h=bd(a);h||(a[Wc]=h=new Uc(a));c=h.add(b,c,d,k,g);if(c.proxy)return c;d=cd();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)Oc||(f=k),void 0===
f&&(f=!1),a.addEventListener(b.toString(),d,f);else if(a.attachEvent)a.attachEvent(dd(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Yc++;return c},cd=function(){var a=ed,b=function(c){return a.call(b.src,b.listener,c)};return b},Zc=function(a,b,c,d,f){if(Array.isArray(b)){for(var g=0;g<b.length;g++)Zc(a,b[g],c,d,f);return null}c=$c(c);return Rc(a)?a.Jc(b,c,cb(d)?!!d.capture:!!d,f):ad(a,b,c,!0,d,f)},fd=
function(a,b,c,d,f){if(Array.isArray(b)){for(var g=0;g<b.length;g++)fd(a,b[g],c,d,f);return null}d=cb(d)?!!d.capture:!!d;c=$c(c);if(Rc(a))return a.Zb(b,c,d,f);if(!a)return!1;if(a=bd(a))if(b=a.$a(b,c,d,f))return gd(b);return!1},gd=function(a){if(typeof a===za||!a||a.mb)return!1;var b=a.src;if(Rc(b))return b.cf(a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(dd(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Yc--;(c=bd(b))?
(c.Pe(a),0==c.qb&&(c.src=null,b[Wc]=null)):a.Qb();return!0},hd=function(a,b){if(!a)return 0;if(Rc(a))return a.Oe(b);a=bd(a);if(!a)return 0;var c=0;b=b&&b.toString();for(var d in a.v)if(!b||d==b)for(var f=a.v[d].concat(),g=0;g<f.length;++g)gd(f[g])&&++c;return c},dd=function(a){return a in Xc?Xc[a]:Xc[a]="on"+a},ed=function(a,b){if(a.mb)a=!0;else{b=new N(b,this);var c=a.listener,d=a.Fb||a.src;a.wb&&gd(a);a=c.call(d,b)}return a},bd=function(a){a=a[Wc];return a instanceof Uc?a:null},id="__closure_events_fn_"+
(1E9*Math.random()>>>0),$c=function(a){if(typeof a===p)return a;a[id]||(a[id]=function(b){return a.handleEvent(b)});return a[id]};var P=function(){K.call(this);this.aa=new Uc(this);this.Nf=this;this.Pc=null};z(P,K);P.prototype[Qc]=!0;v=P.prototype;v.addEventListener=function(a,b,c,d){O(this,a,b,c,d)};v.removeEventListener=function(a,b,c,d){fd(this,a,b,c,d)};
v.dispatchEvent=function(a){var b=this.Pc;if(b){var c=[];for(var d=1;b;b=b.Pc)c.push(b),++d}b=this.Nf;d=a.type||a;if(typeof a===u)a=new L(a,b);else if(a instanceof L)a.target=a.target||b;else{var f=a;a=new L(d,b);Tb(a,f)}f=!0;if(c)for(var g=c.length-1;!a.kb&&0<=g;g--){var k=a.currentTarget=c[g];f=k.Bb(d,!0,a)&&f}a.kb||(k=a.currentTarget=b,f=k.Bb(d,!0,a)&&f,a.kb||(f=k.Bb(d,!1,a)&&f));if(c)for(g=0;!a.kb&&g<c.length;g++)k=a.currentTarget=c[g],f=k.Bb(d,!1,a)&&f;return f};
v.m=function(){P.u.m.call(this);this.Oe();this.Pc=null};v.Pa=function(a,b,c,d){return this.aa.add(String(a),b,!1,c,d)};v.Jc=function(a,b,c,d){return this.aa.add(String(a),b,!0,c,d)};v.Zb=function(a,b,c,d){return this.aa.remove(String(a),b,c,d)};v.cf=function(a){return this.aa.Pe(a)};v.Oe=function(a){return this.aa?this.aa.Ub(a):0};
v.Bb=function(a,b,c){a=this.aa.v[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,f=0;f<a.length;++f){var g=a[f];if(g&&!g.mb&&g.capture==b){var k=g.listener,h=g.Fb||g.src;g.wb&&this.cf(g);d=!1!==k.call(h,c)&&d}}return d&&!c.defaultPrevented};v.$a=function(a,b,c,d){return this.aa.$a(String(a),b,c,d)};v.hasListener=function(a,b){return this.aa.hasListener(void 0!==a?String(a):void 0,b)};var jd=function(a){try{return w.JSON.parse(a)}catch(b){}a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};var kd=function(){};kd.prototype.Ld=null;kd.prototype.fe=function(){return this.Ld||(this.Ld=this.Og())};var ld,md=function(){};z(md,kd);md.prototype.Pd=function(){var a=this.ge();return a?new ActiveXObject(a):new XMLHttpRequest};md.prototype.Og=function(){var a={};this.ge()&&(a[0]=!0,a[1]=!0);return a};
md.prototype.ge=function(){if(!this.le&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var a=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],b=0;b<a.length;b++){var c=a[b];try{return new ActiveXObject(c),this.le=c}catch(d){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return this.le};ld=new md;var nd=function(a,b,c){if(typeof a===p)c&&(a=x(a,c));else if(a&&typeof a.handleEvent==p)a=x(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:w.setTimeout(a,b||0)};var od=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$"),pd=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),f=null;if(0<=d){var g=a[c].substring(0,d);f=a[c].substring(d+1)}else g=a[c];b(g,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}};var Q=function(a){P.call(this);this.headers=new Map;this.cc=a||null;this.ja=!1;this.bc=this.g=null;this.Ic="";this.Oa=0;this.ya=this.Ac=this.Ib=this.qc=!1;this.Ba=0;this.Yb=null;this.Ra="";this.od=this.Dh=this.ha=!1;this.md=null};z(Q,P);var qd=/^https?$/i,rd=["POST","PUT"],sd=[],td=function(a,b,c,d,f,g,k){var h=new Q;sd.push(h);b&&h.Pa(e,b);h.Jc(Ba,h.Zf);g&&h.gd(g);k&&h.jd(k);h.send(a,c,d,f);return h};v=Q.prototype;v.Zf=function(){this.ra();sb(sd,this)};v.gd=function(a){this.Ba=Math.max(0,a)};
v.Mh=function(a){this.Ra=a};v.jd=function(a){this.ha=a};v.setTrustToken=function(a){this.md=a};
v.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.Ic+"; newUri="+a);b=b?b.toUpperCase():"GET";this.Ic=a;this.Oa=0;this.qc=!1;this.ja=!0;this.g=this.cg();this.bc=this.cc?this.cc.fe():ld.fe();this.g.onreadystatechange=x(this.Ie,this);this.Dh&&"onprogress"in this.g&&(this.g.onprogress=x(function(k){this.Ge(k,!0)},this),this.g.upload&&(this.g.upload.onprogress=x(this.Ge,this)));try{this.Ac=!0,this.g.open(b,String(a),!0),this.Ac=!1}catch(k){this.Yd(5,
k);return}a=c||"";c=new Map(this.headers);if(d)if(Object.getPrototypeOf(d)===Object.prototype)for(var f in d)c.set(f,d[f]);else if(typeof d.keys===p&&typeof d.get===p){f=Pa(d.keys());for(var g=f.next();!g.done;g=f.next())g=g.value,c.set(g,d.get(g))}else throw Error("Unknown input type for opt_headers: "+String(d));d=Array.from(c.keys()).find(function(k){return"content-type"==k.toLowerCase()});f=w.FormData&&a instanceof w.FormData;!A(rd,b)||d||f||c.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
b=Pa(c);for(d=b.next();!d.done;d=b.next())c=Pa(d.value),d=c.next().value,c=c.next().value,this.g.setRequestHeader(d,c);this.Ra&&(this.g.responseType=this.Ra);"withCredentials"in this.g&&this.g.withCredentials!==this.ha&&(this.g.withCredentials=this.ha);if("setTrustToken"in this.g&&this.md)try{this.g.setTrustToken(this.md)}catch(k){}try{this.Md(),0<this.Ba&&((this.od=ud(this.g))?(this.g.timeout=this.Ba,this.g.ontimeout=x(this.bf,this)):this.Yb=nd(this.bf,this.Ba,this)),this.Ib=!0,this.g.send(a),this.Ib=
!1}catch(k){this.Yd(5,k)}};var ud=function(a){return D&&Jb(9)&&typeof a.timeout===za&&void 0!==a.ontimeout};v=Q.prototype;v.cg=function(){return this.cc?this.cc.Pd():ld.Pd()};v.bf=function(){"undefined"!=typeof Za&&this.g&&(this.Oa=8,this.dispatchEvent("timeout"),this.abort(8))};v.Yd=function(a){this.ja=!1;this.g&&(this.ya=!0,this.g.abort(),this.ya=!1);this.Oa=a;this.Ud();this.yb()};v.Ud=function(){this.qc||(this.qc=!0,this.dispatchEvent(e),this.dispatchEvent("error"))};
v.abort=function(a){this.g&&this.ja&&(this.ja=!1,this.ya=!0,this.g.abort(),this.ya=!1,this.Oa=a||7,this.dispatchEvent(e),this.dispatchEvent("abort"),this.yb())};v.m=function(){this.g&&(this.ja&&(this.ja=!1,this.ya=!0,this.g.abort(),this.ya=!1),this.yb(!0));Q.u.m.call(this)};v.Ie=function(){this.Ea||(this.Ac||this.Ib||this.ya?this.He():this.yh())};v.yh=function(){this.He()};
v.He=function(){if(this.ja&&"undefined"!=typeof Za&&(!this.bc[1]||4!=this.Db()||2!=this.getStatus()))if(this.Ib&&4==this.Db())nd(this.Ie,0,this);else if(this.dispatchEvent("readystatechange"),this.Cc()){this.ja=!1;try{this.gb()?(this.dispatchEvent(e),this.dispatchEvent(Ia)):(this.Oa=6,this.Ud())}finally{this.yb()}}};v.Ge=function(a,b){this.dispatchEvent(vd(a,"progress"));this.dispatchEvent(vd(a,b?"downloadprogress":"uploadprogress"))};
var vd=function(a,b){return{type:b,lengthComputable:a.lengthComputable,loaded:a.loaded,total:a.total}};v=Q.prototype;v.yb=function(a){if(this.g){this.Md();var b=this.g,c=this.bc[0]?$a:null;this.bc=this.g=null;a||this.dispatchEvent(Ba);try{b.onreadystatechange=c}catch(d){}}};v.Md=function(){this.g&&this.od&&(this.g.ontimeout=null);this.Yb&&(w.clearTimeout(this.Yb),this.Yb=null)};v.Lb=function(){return!!this.g};v.Cc=function(){return 4==this.Db()};
v.gb=function(){var a=this.getStatus();a:switch(a){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var b=!0;break a;default:b=!1}return b||0===a&&!this.Rg()};v.Rg=function(){var a=String(this.Ic).match(od)[1]||null;!a&&w.self&&w.self.location&&(a=w.self.location.protocol,a=a.substr(0,a.length-1));return qd.test(a?a.toLowerCase():"")};v.Db=function(){return this.g?this.g.readyState:0};v.getStatus=function(){try{return 2<this.Db()?this.g.status:-1}catch(a){return-1}};
v.he=function(a){if(this.g){var b=this.g.responseText;a&&0==b.indexOf(a)&&(b=b.substring(a.length));a:{a=b;if(w.JSON)try{var c=w.JSON.parse(a);break a}catch(d){}c=jd(a)}return c}};v.rg=function(){try{if(!this.g)return null;if("response"in this.g)return this.g.response;switch(this.Ra){case "":case "text":return this.g.responseText;case "arraybuffer":if("mozResponseArrayBuffer"in this.g)return this.g.mozResponseArrayBuffer}return null}catch(a){return null}};
v.getResponseHeader=function(a){if(this.g&&this.Cc())return a=this.g.getResponseHeader(a),null===a?void 0:a};v.getAllResponseHeaders=function(){return this.g&&this.Cc()?this.g.getAllResponseHeaders()||"":""};var wd=function(){};wd.prototype.da=function(){return"NONE"};wd.prototype.za=function(){return null};wd.prototype.qe=function(){return!1};var xd=function(a){this.label=a};z(xd,wd);xd.prototype.X=function(){return this.label};var R=function(a,b,c){this.label=b;this.value=a.da();this.Qg=c;this.rc=a};z(R,wd);v=R.prototype;v.X=function(){return this.label};v.da=function(){return this.value};v.qe=function(){return this.Qg};v.encode=function(){return this.rc.encode()+"="};v.za=function(){return new yd(this)};var zd=function(){};z(zd,wd);zd.prototype.encode=function(){return encodeURIComponent(this.da())};zd.prototype.za=function(){return null};var Ad=function(a){R.call(this,a,a.X(),!0)};z(Ad,R);var Bd=function(){};z(Bd,zd);Bd.prototype.X=function(){return"Anonymous"};Bd.prototype.da=function(){return"ANON"};Bd.prototype.decode=function(){return new Ad(this)};var Cd=function(a){if(a.o&&typeof a.o==p)a=a.o();else if(bb(a)||typeof a===u)a=a.length;else{var b=0,c;for(c in a)b++;a=b}return a},Dd=function(a){if(a.F&&typeof a.F==p)return a.F();if("undefined"!==typeof Map&&a instanceof Map||"undefined"!==typeof Set&&a instanceof Set)return Array.from(a.values());if(typeof a===u)return a.split("");if(bb(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ob(a)},Ed=function(a){if(a.ma&&typeof a.ma==p)return a.ma();if(!a.F||typeof a.F!=p){if("undefined"!==
typeof Map&&a instanceof Map)return Array.from(a.keys());if(!("undefined"!==typeof Set&&a instanceof Set)){if(bb(a)||typeof a===u){var b=[];a=a.length;for(var c=0;c<a;c++)b.push(c);return b}return Pb(a)}}},Fd=function(a,b,c){if(a.forEach&&typeof a.forEach==p)a.forEach(b,c);else if(bb(a)||typeof a===u)Array.prototype.forEach.call(a,b,c);else for(var d=Ed(a),f=Dd(a),g=f.length,k=0;k<g;k++)b.call(c,f[k],d&&d[k],a)},Gd=function(a,b,c){if(typeof a.every==p)return a.every(b,c);if(bb(a)||typeof a===u)return Array.prototype.every.call(a,
b,c);for(var d=Ed(a),f=Dd(a),g=f.length,k=0;k<g;k++)if(!b.call(c,f[k],d&&d[k],a))return!1;return!0};var Hd=function(a,b){this.Ya=this.rb=this.qa="";this.Qa=null;this.ta=this.Qc="";this.J=this.Sg=!1;var c;a instanceof Hd?(this.J=void 0!==b?b:a.J,this.fd(a.qa),this.hd(a.rb),this.ad(a.Ya),this.dd(a.Qa),this.setPath(a.getPath()),this.ed(a.S.clone()),this.bd(a.ta)):a&&(c=String(a).match(od))?(this.J=!!b,this.fd(c[1]||"",!0),this.hd(c[2]||"",!0),this.ad(c[3]||"",!0),this.dd(c[4]),this.setPath(c[5]||"",!0),this.ed(c[6]||"",!0),this.bd(c[7]||"",!0)):(this.J=!!b,this.S=new Id(null,this.J))};v=Hd.prototype;
v.toString=function(){var a=[],b=this.qa;b&&a.push(Jd(b,Kd,!0),":");var c=this.Ya;if(c||"file"==b)a.push("//"),(b=this.rb)&&a.push(Jd(b,Kd,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.Qa,null!=c&&a.push(":",String(c));if(c=this.getPath())this.uc()&&"/"!=c.charAt(0)&&a.push("/"),a.push(Jd(c,"/"==c.charAt(0)?Ld:Md,!0));(c=this.ae())&&a.push("?",c);(c=this.ta)&&a.push("#",Jd(c,Nd));return a.join("")};
v.resolve=function(a){var b=this.clone(),c=a.Gg();c?b.fd(a.qa):c=a.Hg();c?b.hd(a.rb):c=a.uc();c?b.ad(a.Ya):c=a.Eg();var d=a.getPath();if(c)b.dd(a.Qa);else if(c=a.ke()){if("/"!=d.charAt(0))if(this.uc()&&!this.ke())d="/"+d;else{var f=b.getPath().lastIndexOf("/");-1!=f&&(d=b.getPath().substr(0,f+1)+d)}f=d;if(".."==f||"."==f)d="";else if(-1!=f.indexOf("./")||-1!=f.indexOf("/.")){d=0==f.lastIndexOf("/",0);f=f.split("/");for(var g=[],k=0;k<f.length;){var h=f[k++];"."==h?d&&k==f.length&&g.push(""):".."==
h?((1<g.length||1==g.length&&""!=g[0])&&g.pop(),d&&k==f.length&&g.push("")):(g.push(h),d=!0)}d=g.join("/")}else d=f}c?b.setPath(d):c=a.Fg();c?b.ed(a.S.clone()):c=a.Dg();c&&b.bd(a.ta);return b};v.clone=function(){return new Hd(this)};v.fd=function(a,b){this.Z();if(this.qa=b?Od(a,!0):a)this.qa=this.qa.replace(/:$/,"");return this};v.Gg=function(){return!!this.qa};v.hd=function(a,b){this.Z();this.rb=b?Od(a):a;return this};v.Hg=function(){return!!this.rb};
v.ad=function(a,b){this.Z();this.Ya=b?Od(a,!0):a;return this};v.uc=function(){return!!this.Ya};v.dd=function(a){this.Z();if(a){a=Number(a);if(isNaN(a)||0>a)throw Error("Bad port number "+a);this.Qa=a}else this.Qa=null;return this};v.Eg=function(){return null!=this.Qa};v.getPath=function(){return this.Qc};v.setPath=function(a,b){this.Z();this.Qc=b?Od(a,!0):a;return this};v.ke=function(){return!!this.Qc};v.Fg=function(){return""!==this.S.toString()};
v.ed=function(a,b){this.Z();a instanceof Id?(this.S=a,this.S.cd(this.J)):(b||(a=Jd(a,Pd)),this.S=new Id(a,this.J));return this};v.ae=function(){return this.S.toString()};v.getQuery=function(){return this.ae()};v.Wb=function(a,b){this.Z();this.S.set(a,b);return this};v.bd=function(a,b){this.Z();this.ta=b?Od(a):a;return this};v.Dg=function(){return!!this.ta};v.removeParameter=function(a){this.Z();this.S.remove(a);return this};
v.Z=function(){if(this.Sg)throw Error("Tried to modify a read-only Uri");};v.cd=function(a){this.J=a;this.S&&this.S.cd(a);return this};
var Od=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},Jd=function(a,b,c){return typeof a===u?(a=encodeURI(a).replace(b,Qd),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},Qd=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Kd=/[#\/\?@]/g,Md=/[#\?:]/g,Ld=/[#\?]/g,Pd=/[#\?@]/g,Nd=/#/g,Id=function(a,b){this.A=this.l=null;this.la=a||null;this.J=!!b};v=Id.prototype;
v.W=function(){if(!this.l&&(this.l=new Map,this.A=0,this.la)){var a=this;pd(this.la,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)})}};v.o=function(){this.W();return this.A};v.add=function(a,b){this.W();this.Ma();a=this.Ja(a);var c=this.l.get(a);c||this.l.set(a,c=[]);c.push(b);this.A+=1;return this};v.remove=function(a){this.W();a=this.Ja(a);return this.l.has(a)?(this.Ma(),this.A-=this.l.get(a).length,this.l.delete(a)):!1};v.clear=function(){this.Ma();this.l=null;this.A=0};
v.isEmpty=function(){this.W();return 0==this.A};v.Da=function(a){this.W();a=this.Ja(a);return this.l.has(a)};v.Wa=function(a){var b=this.F();return A(b,a)};v.forEach=function(a,b){this.W();this.l.forEach(function(c,d){c.forEach(function(f){a.call(b,f,d,this)},this)},this)};v.ma=function(){this.W();for(var a=Array.from(this.l.values()),b=Array.from(this.l.keys()),c=[],d=0;d<b.length;d++)for(var f=a[d],g=0;g<f.length;g++)c.push(b[d]);return c};
v.F=function(a){this.W();var b=[];if(typeof a===u)this.Da(a)&&(b=b.concat(this.l.get(this.Ja(a))));else{a=Array.from(this.l.values());for(var c=0;c<a.length;c++)b=b.concat(a[c])}return b};v.set=function(a,b){this.W();this.Ma();a=this.Ja(a);this.Da(a)&&(this.A-=this.l.get(a).length);this.l.set(a,[b]);this.A+=1;return this};v.get=function(a,b){if(!a)return b;a=this.F(a);return 0<a.length?String(a[0]):b};
v.setValues=function(a,b){this.remove(a);0<b.length&&(this.Ma(),this.l.set(this.Ja(a),tb(b)),this.A+=b.length)};v.toString=function(){if(this.la)return this.la;if(!this.l)return"";for(var a=[],b=Array.from(this.l.keys()),c=0;c<b.length;c++){var d=b[c],f=encodeURIComponent(String(d));d=this.F(d);for(var g=0;g<d.length;g++){var k=f;""!==d[g]&&(k+="="+encodeURIComponent(String(d[g])));a.push(k)}}return this.la=a.join("&")};v.Ma=function(){this.la=null};
v.clone=function(){var a=new Id;a.la=this.la;this.l&&(a.l=new Map(this.l),a.A=this.A);return a};v.Ja=function(a){a=String(a);this.J&&(a=a.toLowerCase());return a};v.cd=function(a){a&&!this.J&&(this.W(),this.Ma(),this.l.forEach(function(b,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.setValues(d,b))},this));this.J=a};v.extend=function(a){for(var b=0;b<arguments.length;b++)Fd(arguments[b],function(c,d){this.add(d,c)},this)};var Rd="";/*

 SPDX-License-Identifier: Apache-2.0
*/
function Sd(a,b){if(null!==a&&void 0!==a.tagName){if("script"===a.tagName.toLowerCase())throw Error("Use setTextContent with a SafeScript.");if("style"===a.tagName.toLowerCase())throw Error("Use setTextContent with a SafeStyleSheet.");}a.innerHTML=b instanceof wc&&b.constructor===wc?b.Tc:"type_error:SafeHtml"};var Td=function(){"loading"!=document.readyState?this.oe():O(window,"load",this.oe)};Td.prototype.oe=function(){for(var a=Pa(Array.prototype.slice.call(document.getElementsByTagName("link"),0)),b=a.next();!b.done;b=a.next())b=b.value,"true"==b.getAttribute("data-async-css")&&b.getAttribute("media")==q&&b.setAttribute("media","all")};var Ud=function(a){return typeof a.className==u?a.className:a.getAttribute&&a.getAttribute("class")||""},Vd=function(a){return a.classList?a.classList:Ud(a).match(/\S+/g)||[]},Wd=function(a,b){typeof a.className==u?a.className=b:a.setAttribute&&a.setAttribute("class",b)},Xd=function(a,b){return a.classList?a.classList.contains(b):A(Vd(a),b)},Yd=function(a,b){if(a.classList)a.classList.add(b);else if(!Xd(a,b)){var c=Ud(a);Wd(a,c+(0<c.length?" "+b:b))}},Zd=function(a,b){a.classList?a.classList.remove(b):
Xd(a,b)&&Wd(a,Array.prototype.filter.call(Vd(a),function(c){return c!=b}).join(" "))};var $d=function(a){K.call(this);this.Ka=a;this.h={}};z($d,K);var ae=[];v=$d.prototype;v.Pa=function(a,b,c,d){return this.Vg(a,b,c,d)};v.Vg=function(a,b,c,d,f){Array.isArray(b)||(b&&(ae[0]=b.toString()),b=ae);for(var g=0;g<b.length;g++){var k=O(a,b[g],c||this.handleEvent,d||!1,f||this.Ka||this);if(!k)break;this.h[k.key]=k}return this};v.Jc=function(a,b,c,d){return this.Ae(a,b,c,d)};
v.Ae=function(a,b,c,d,f){if(Array.isArray(b))for(var g=0;g<b.length;g++)this.Ae(a,b[g],c,d,f);else{a=Zc(a,b,c||this.handleEvent,d,f||this.Ka||this);if(!a)return this;this.h[a.key]=a}return this};v.Zb=function(a,b,c,d,f){if(Array.isArray(b))for(var g=0;g<b.length;g++)this.Zb(a,b[g],c,d,f);else c=c||this.handleEvent,d=cb(d)?!!d.capture:!!d,f=f||this.Ka||this,c=$c(c),d=!!d,b=Rc(a)?a.$a(b,c,d,f):a?(a=bd(a))?a.$a(b,c,d,f):null:null,b&&(gd(b),delete this.h[b.key]);return this};
v.Ub=function(){Lb(this.h,function(a,b){this.h.hasOwnProperty(b)&&gd(a)},this);this.h={}};v.m=function(){$d.u.m.call(this);this.Ub()};v.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var be=function(a){var b=a.offsetWidth,c=a.offsetHeight,d=F&&!b&&!c;if((void 0===b||d)&&a.getBoundingClientRect){try{var f=a.getBoundingClientRect()}catch(g){f={left:0,top:0,right:0,bottom:0}}return new zc(f.right-f.left,f.bottom-f.top)}return new zc(b,c)},ce=function(a,b){a.style.display=b?"":q},ee=function(a,b){b=Ec(b);var c=b.sa;if(D&&c.createStyleSheet)return b=c.createStyleSheet(),de(b,a),b;c=b.$d("HEAD")[0];if(!c){var d=b.$d("BODY")[0];c=b.lc("HEAD");d.parentNode.insertBefore(c,d)}d=b.lc("STYLE");
var f=yc('style[nonce],link[rel="stylesheet"][nonce]',void 0);f&&d.setAttribute("nonce",f);de(d,a);b.appendChild(c,d);return d},de=function(a,b){b=tc(b);if(D&&void 0!==a.cssText)a.cssText=b;else if(w.trustedTypes)if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else Mc(a),a.appendChild(Dc(a).createTextNode(String(b)));else a.innerHTML=b};/*

 CC0 1.0 Universal License
 Public Domain Dedication

 The person(s) who associated a work with this deed has dedicated the work to
 the public domain by waiving all of his or her rights to the work worldwide
 under copyright law, including all related and neighboring rights, to the
 extent allowed by law.

 You can copy, modify, distribute and perform the work, even for commercial
 purposes, all without asking permission.

 In no way are the patent or trademark rights of any person affected by CC0,
 nor are the rights that other persons may have in the work or in how the work
 is used, such as publicity or privacy rights.

 Unless expressly stated otherwise, the person(s) who associated a work with
 this deed makes no warranties about the work, and disclaims liability for all
 uses of the work, to the fullest extent permitted by applicable law.

 When using or citing the work, you should not imply endorsement by the author
 or the affirmer.

 This is a human-readable summary of the Legal Code (read the full text).
 svg4everybody v2.1.8 | github.com/jonathantneal/svg4everybody */
function fe(a,b,c){if(c){var d=document.createDocumentFragment(),f=!b.hasAttribute("viewBox")&&c.getAttribute("viewBox");f&&b.setAttribute("viewBox",f);for(b=c.cloneNode(!0);b.childNodes.length;)d.appendChild(b.firstChild);a.appendChild(d)}}
function ge(a){a.onreadystatechange=function(){if(4===a.readyState){var b=a.Mf;b||(b=a.Mf=document.implementation.createHTMLDocument(""),b.body.innerHTML=a.responseText,a.zd={});a.Ad.splice(0).map(function(c){var d=a.zd[c.id];d||(d=a.zd[c.id]=b.getElementById(c.id));fe(c.parent,c.Qh,d)})}};a.onreadystatechange()}function he(){return"undefined"!=typeof LEGACY_SUPPORT&&LEGACY_SUPPORT}
var ie=function(a){function b(){for(var pa=0;pa<Mb.length;){var G=Mb[pa],ib=G.parentNode,C;for(C=ib;"svg"!==C.nodeName.toLowerCase()&&(C=C.parentNode,C););if(C){var M=G.getAttribute("xlink:href")||G.getAttribute("href");!M&&c.attributeName&&(M=G.getAttribute(c.attributeName));if(he()&&f){var H=document.createElement("img");H.style.cssText="display:inline-block;height:100%;width:100%";H.setAttribute("width",C.getAttribute("width")||C.clientWidth);H.setAttribute("height",C.getAttribute("height")||C.clientHeight);
H.src=d(M,C,G);ib.replaceChild(H,G)}else t&&(!c.validate||c.validate(M,C,G)?(ib.removeChild(G),M=M.split("#"),G=M.shift(),M=M.join("#"),G.length?(H=W[G],H||(H=W[G]=new XMLHttpRequest,H.open("GET",G),H.send(),H.Ad=[]),H.Ad.push({parent:ib,Qh:C,id:M}),ge(H)):fe(ib,C,document.getElementById(M))):(++pa,++je))}else++pa}if(!Mb.length||0<Mb.length-je)window.requestAnimationFrame?window.requestAnimationFrame(b):setTimeout(b,67)}var c=Object(a);if(he()){var d=c.Vh||function(pa){return pa.replace(/\?[^#]+/,
"").replace("#",".").replace(/^\./,"")+".png"+(/\?[^#]+/.exec(pa)||[""])[0]};var f="nosvg"in c?c.Wh:/\bMSIE [1-8]\b/.test(navigator.userAgent)}a=/\bMSIE [1-8]\.0\b/;var g=/\bTrident\/[567]\b|\bMSIE (?:9|10)\.0\b/,k=/\bAppleWebKit\/(\d+)\b/,h=/\bEdge\/12\.(\d+)\b/,m=/\bEdge\/.(\d+)\b/,n=window.top!==window.self;var t="polyfill"in c?c.Xh:he()?a.test(navigator.userAgent)||g.test(navigator.userAgent)||10547>(navigator.userAgent.match(h)||[])[1]||537>(navigator.userAgent.match(k)||[])[1]||m.test(navigator.userAgent)&&
n:g.test(navigator.userAgent)||10547>(navigator.userAgent.match(h)||[])[1]||537>(navigator.userAgent.match(k)||[])[1]||m.test(navigator.userAgent)&&n;var W={},Mb=document.getElementsByTagName("use"),je=0;t&&b()};var ke=function(a){return/^[A-Za-z0-9]+$/.test(a)||/^#[0-9A-Fa-f]{3}$/.test(a)||/^#[0-9A-Fa-f]{6}$/.test(a)||RegExp("^rgb *\\( *\\d{1,3}%? *, *\\d{1,3}%? *, *\\d{1,3}%? *\\)$").test(a)||RegExp("^rgba *\\( *\\d{1,3}%? *, *\\d{1,3}%? *, *\\d{1,3}%? *, *\\d{1,3}%? *\\)$").test(a)},le=function(a){a=a.split(",");for(var b=0;b<a.length;b++){var c=a[b];c=ub(c);if(!(/^[- A-Za-z0-9]*$/.test(c)||/^"[- A-Za-z0-9]*"$/.test(c)||/^'[- A-Za-z0-9]*'$/.test(c)))return!1}return!0},me=function(){if(window.parent&&window.parent.postMessage){var a=
document.getElementById("previewHolder"),b=0;if(a){b:{b=Dc(a);if(b.defaultView&&b.defaultView.getComputedStyle&&(b=b.defaultView.getComputedStyle(a,null))){b=b.display||b.getPropertyValue("display")||"";break b}b=""}if((b||(a.currentStyle?a.currentStyle.display:null)||a.style&&a.style.display)!=q)a=be(a);else{b=a.style;var c=b.display,d=b.visibility,f=b.position;b.visibility=qa;b.position="absolute";b.display="inline";a=be(a);b.display=c;b.position=f;b.visibility=d}b=a.height}a=document.getElementById(ea);
c=0;a&&(c=a.offsetHeight);b=(b=Math.max(b,c||document.body.offsetHeight))||230;a="amp=1"==(new Hd(document.location.href)).ta?{sentinel:"amp",type:"embed-size",height:b}:"set-comment-editor-height "+b+"px";window.parent.postMessage(a,"*")}},ne=function(){var a=document.getElementById(ia),b=document.getElementById(Aa),c=document.getElementById("postCommentPreview"),d=function(){b&&(b.disabled=""==a.value);c&&(c.disabled=""==a.value)};a&&"oninput"in a&&(d(null),O(a,"input",d))},oe=function(a){var b=
[];D&&b.push(sc(".previewMode .postCommentButtonHolder",{"padding-top":"22px"}));var c=(new Hd(a)).ta;if(0!=c.length){a=null;try{c=decodeURIComponent(c),a=JSON.parse(c)}catch(k){}if(a&&a.color){c=Bc(Ac(a.color));var d=Bc(Ac(a.unvisitedLinkColor));a=Bc(Ac(a.fontFamily));ke(c)&&ke(d)&&le(a)&&(b.push(sc("body",{color:c,"font-family":a})),b.push(sc("a:link, a:visited, a:active, a:hover",{color:d})))}}ee(uc(b));setTimeout(me,100);var f=J(ea);if((b=J(ia))&&f){var g=!1;O(b,"focus",function(){g||(g=!0,Zd(f,
"compact"),me())})}ie();new Td};var pe=function(a){a=J(a);var b=a.nodeName.toLowerCase();a.style.display="span"==b||"img"==b||"a"==b||"input"==b||"select"==b?"inline":"block"},S=function(a){J(a).style.display=q};var re=function(a){qe();var b=Vb();a=b?b.createHTML(a):a;return new wc(a,null,vc)},qe=$a;var T=function(a,b,c){c&&S(xa);switch(a){case 0:var d=a="captcha-error";break;case 1:d=a="id-error";break;case 2:case 3:case 4:d="main-error";a="main-error-holder";break;case 5:d=a="nameUrlDialogErrorHolder";break;default:throw Error("internal error in show message");}c?(c=Fc(document,d),Sd(c,re(String(b))),pe(a),J(ia).className="commentBody-err"):(Mc(J(d)),S(a));me()},se=function(a){T(3,null,!1);Sd(J("main-status"),re(a));pe(xa);me()};function te(){}te.prototype.Ph=function(){S(ta);J(ia).disabled=!0;J(Aa).disabled=!0};te.prototype.Ig=function(){pe(ta);J(ia).disabled=!1;J(Aa).disabled=!1};var yd=function(a){this.wa=a};z(yd,te);v=yd.prototype;v.fb=function(){return!1};v.Xb=function(){if(!this.fb())throw Error("Trying to show a non-editable identity");this.Ph();pe(sa)};v.te=function(){return!0};v.kd=function(){if(!this.fb())throw Error("Trying to show edit button for a non-editable identity");pe("editButton")};v.Ne=function(){};v.$c=function(){};v.ab=function(){S(sa);S("editButton");S("settingsButton");S("commentDash");S(Ha);this.Ig()};var ue=function(a){a=a.className;return typeof a===u&&a.match(/\S+/g)||[]},ve=function(a,b){for(var c=ue(a),d=Array.prototype.slice.call(arguments,1),f=c.length+d.length,g=0;g<d.length;g++)A(c,d[g])||c.push(d[g]);a.className=c.join(" ");return c.length==f},xe=function(a,b){var c=ue(a),d=Array.prototype.slice.call(arguments,1),f=we(c,d);a.className=f.join(" ");return f.length==c.length-d.length},we=function(a,b){return a.filter(function(c){return!A(b,c)})};var ye=function(a,b){this.Yf=a[w.Symbol.iterator]();this.Yg=b;this.fh=0};ye.prototype[Symbol.iterator]=function(){return this};ye.prototype.next=function(){var a=this.Yf.next();return{value:a.done?void 0:this.Yg.call(void 0,a.value,this.fh++),done:a.done}};var ze=function(a,b){return new ye(a,b)};var Ae="StopIteration"in w?w.StopIteration:{message:"StopIteration",stack:""},Be=function(){};Be.prototype.Sb=function(){throw Ae;};Be.prototype.next=function(){return Ce};var Ce={done:!0,value:void 0};Be.prototype.ia=function(){return this};var Ge=function(a){if(a instanceof U||a instanceof De||a instanceof Ee)return a;if(typeof a.Sb==p)return new U(function(){return Fe(a)});if(typeof a[Symbol.iterator]==p)return new U(function(){return a[Symbol.iterator]()});if(typeof a.ia==p)return new U(function(){return Fe(a.ia())});throw Error("Not an iterator or iterable.");},Fe=function(a){if(!(a instanceof Be))return a;var b=!1;return{next:function(){for(var c;!b;)try{c=a.Sb();break}catch(d){if(d!==Ae)throw d;b=!0}return{value:c,done:b}}}},U=
function(a){this.sc=a};U.prototype.ia=function(){return new De(this.sc())};U.prototype[Symbol.iterator]=function(){return new Ee(this.sc())};U.prototype.ld=function(){return new Ee(this.sc())};var De=function(a){this.Na=a};Wa(De,Be);De.prototype.Sb=function(){var a=this.Na.next();if(a.done)throw Ae;return a.value};De.prototype.next=function(){return this.Na.next()};De.prototype[Symbol.iterator]=function(){return new Ee(this.Na)};De.prototype.ld=function(){return new Ee(this.Na)};
var Ee=function(a){U.call(this,function(){return a});this.Na=a};Wa(Ee,U);Ee.prototype.next=function(){return this.Na.next()};var He=function(a,b){this.i={};this.h=[];this.sb=this.size=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.addAll(a)};v=He.prototype;v.o=function(){return this.size};v.F=function(){this.Va();for(var a=[],b=0;b<this.h.length;b++)a.push(this.i[this.h[b]]);return a};v.ma=function(){this.Va();return this.h.concat()};v.Da=function(a){return this.has(a)};v.has=function(a){return Ie(this.i,a)};
v.Wa=function(a){for(var b=0;b<this.h.length;b++){var c=this.h[b];if(Ie(this.i,c)&&this.i[c]==a)return!0}return!1};v.equals=function(a,b){if(this===a)return!0;if(this.size!=a.o())return!1;b=b||Je;this.Va();for(var c,d=0;c=this.h[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};var Je=function(a,b){return a===b};v=He.prototype;v.isEmpty=function(){return 0==this.size};v.clear=function(){this.i={};this.h.length=0;this.ga(0);this.sb=0};v.remove=function(a){return this.delete(a)};
v.delete=function(a){return Ie(this.i,a)?(delete this.i[a],this.ga(this.size-1),this.sb++,this.h.length>2*this.size&&this.Va(),!0):!1};v.Va=function(){if(this.size!=this.h.length){for(var a=0,b=0;a<this.h.length;){var c=this.h[a];Ie(this.i,c)&&(this.h[b++]=c);a++}this.h.length=b}if(this.size!=this.h.length){var d={};for(b=a=0;a<this.h.length;)c=this.h[a],Ie(d,c)||(this.h[b++]=c,d[c]=1),a++;this.h.length=b}};v.get=function(a,b){return Ie(this.i,a)?this.i[a]:b};
v.set=function(a,b){Ie(this.i,a)||(this.ga(this.size+1),this.h.push(a),this.sb++);this.i[a]=b};v.addAll=function(a){if(a instanceof He)for(var b=a.ma(),c=0;c<b.length;c++)this.set(b[c],a.get(b[c]));else for(b in a)this.set(b,a[b])};v.forEach=function(a,b){for(var c=this.ma(),d=0;d<c.length;d++){var f=c[d],g=this.get(f);a.call(b,g,f,this)}};v.clone=function(){return new He(this)};v.og=function(){return this.ia(!0)};v.keys=function(){return Ge(this.og()).ld()};v.ug=function(){return this.ia(!1)};
v.values=function(){return Ge(this.ug()).ld()};v.entries=function(){var a=this;return ze(this.keys(),function(b){return[b,a.get(b)]})};v.ia=function(a){this.Va();var b=0,c=this.sb,d=this,f=new Be;f.next=function(){if(c!=d.sb)throw Error("The map has changed since the iterator was created");if(b>=d.h.length)return Ce;var k=d.h[b++];return{value:a?k:d.i[k],done:!1}};var g=f.next;f.Sb=function(){var k=g.call(f);if(k.done)throw Ae;return k.value};return f};v.ga=function(a){this.size=a};
var Ie=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var Me=function(a){for(var b=[],c=Ke,d=a.elements,f,g=0;f=d.item(g);g++)if(f.form==a&&!f.disabled&&"FIELDSET"!=f.tagName){var k=f.name;switch(f.type.toLowerCase()){case "file":case "submit":case "reset":case "button":break;case Ea:f=Le(f);if(null!=f)for(var h,m=0;h=f[m];m++)c(b,k,h);break;default:h=Le(f),null!=h&&c(b,k,h)}}d=a.getElementsByTagName(aa);for(g=0;f=d[g];g++)f.form==a&&"image"==f.type.toLowerCase()&&(k=f.name,c(b,k,f.value),c(b,k+".x","0"),c(b,k+".y","0"));return b.join("&")},Ke=function(a,
b,c){a.push(encodeURIComponent(b)+"="+encodeURIComponent(c))},Le=function(a){var b=a.type;if(typeof b===u)switch(b.toLowerCase()){case "checkbox":case "radio":return a.checked?a.value:null;case "select-one":return b=a.selectedIndex,0<=b?a.options[b].value:null;case Ea:b=[];for(var c,d=0;c=a.options[d];d++)c.selected&&b.push(c.value);return b.length?b:null}return null!=a.value?a.value:null};var Ne=!1,Oe=!1,Pe=!1,Qe=function(a,b){Oe=a;Pe=b;window.parent==window.top&&(a||b)?(a=J(Ha),b?ve(a,"checked"):xe(a,"checked"),pe(Ha),J("ajaxAction").value=b?"UnsubscribeByEmail":"SubscribeByEmail"):S(Ha)};var Se=function(a,b){R.call(this,new Re,a,!1);this.kg=b};z(Se,R);Se.prototype.encode=function(){return this.rc.encode()+"="+this.label+"="+this.kg};Se.prototype.X=function(){return this.label+" (Google)"};Se.prototype.za=function(){return new Te(this)};var Re=function(){};z(Re,zd);Re.prototype.X=function(){return""};Re.prototype.da=function(){return"CURRENT"};Re.prototype.decode=function(a){return new Se(a[1],a[2])};Re.prototype.za=function(){throw Error("internal error");};
var Te=function(a){this.wa=a};z(Te,yd);Te.prototype.kd=function(){(Oe||Pe)&&pe(Ha)};var Ue=function(a){R.call(this,a,a.X(),!1)};z(Ue,R);var Ve=function(){};z(Ve,zd);Ve.prototype.X=function(){return"Google Account"};Ve.prototype.da=function(){return"GOOGLE"};Ve.prototype.decode=function(){return this.ee()};Ve.prototype.ee=function(){return new Ue(this)};var We=function(a,b,c){R.call(this,a,null,!0);this.name=b;this.url=c};z(We,R);We.prototype.X=function(){return this.name+" ("+this.url+")"};We.prototype.encode=function(){return this.rc.encode()+"="+encodeURIComponent(this.name)+"="+encodeURIComponent(this.url)};We.prototype.za=function(){return new Xe(this)};var Ye=function(){};z(Ye,zd);Ye.prototype.X=function(){return"Name/URL"};Ye.prototype.da=function(){return"NAMEURL"};Ye.prototype.za=function(){return new Xe(new We(this,"",""))};
Ye.prototype.decode=function(a){return new We(this,a[1],a[2])};var Xe=function(a){this.wa=a};z(Xe,yd);v=Xe.prototype;v.fb=function(){return!0};v.Xb=function(){Xe.u.Xb.call(this);pe(ya)};v.ab=function(){Xe.u.ab.call(this);S(ya);T(5,null,!1);this.Xe("");this.Ze("")};v.Ne=function(){this.Xe(this.wa.name);this.Ze(this.wa.url)};v.$c=function(){Xe.u.$c.call(this);this.wa.name=this.de();this.wa.url=this.tg();this.kd()};v.te=function(){return""==this.de()?(T(5,"Name should not be empty",!0),!1):!0};
v.de=function(){return J("anonNameField").value};v.Xe=function(a){J("anonNameField").value=a};v.tg=function(){return J("anonUrlField").value};v.Ze=function(a){J("anonUrlField").value=a};var Ze=function(){this.va=[];this.ib=[];this.Ua=[];this.cb=[];this.s=this.G=null;this.L=[]};v=Ze.prototype;v.Kb=function(a,b,c,d){for(var f=0;f<this.L.length;f++)if(a==this.L[f])return d(a);d=a.encode();for(f=0;f<this.L.length;f++)if(this.L[f].encode()==d)return c(this.L[f]);return b(a)};v.Ng=function(a){return this.Kb(a,x(function(b){return this.L[this.L.length]=b},this),Kb,Kb)};v.Dc=function(a){function b(){return!1}return this.Kb(a,function(){return!0},b,b)};
v.eb=function(a){function b(){throw Error("item should have been unique");}this.Kb(a,$a,b,b);return this.Ng(a)};v.hc=function(a){return this.Kb(a,x(function(b){this.L[this.L.length]=b;return this.va[this.va.length]=b},this),Kb,Kb)};v.Be=function(){for(var a=document.getElementById("identityControlsHolder"),b=Vd(a),c=0;c<b.length;c++)b[c].slice(0,14)==ra&&Zd(a,b[c]);b=J(ta);(b=this.cb[b.selectedIndex])&&Yd(a,ra+b.value)};v.Dd=function(a){this.G=this.hc(a);this.lb();this.Ta();this.vb(!1);return this.G};
v.Ed=function(a){this.eb(a);this.ib[this.ib.length]=a};v.Qf=function(){var a=this.eb(new Ve);this.Ed(a.ee())};v.Pf=function(){var a=new Ye;this.eb(a);this.Ua[this.Ua.length]=a};v.Of=function(){var a=this.eb(new Bd);a=this.eb(new Ad(a));this.Ua[this.Ua.length]=a};v.Ta=function(){var a=J(ta);a=this.cb[a.selectedIndex];if(a.constructor==xd)this.lb();else{T(1,null,!1);this.s=a.za();null!=this.s&&this.s.Ne();this.Be();var b=J("anonymousWarning");b&&(ce(b,a.qe()),me())}};
v.vb=function(a){if(null!=this.s){var b=this.s.wa;if(a&&this.s.fb()&&this.Dc(b)||!this.s.te())this.s.Xb();else return this.s.$c(),this.s.ab(),this.s.fb()&&this.s.kd(),this.s=null,b}return null};v.Gh=function(){this.dg(J("encodedIds").value);this.G=this.Rd(J(la).value);null==this.G&&0<this.va.length&&(this.G=this.va[0]);null==this.G&&1==this.ib.length&&(this.G=this.ib[0]);this.lb();null!=this.G&&(this.Ta(),this.vb(!1))};
v.Fd=function(a,b){this.cb[this.cb.length]=b;var c=document.createElement("option");c.text=b.X();c.value=b.da();try{a.add(c,null)}catch(d){a.add(c)}this.G==b&&(c.selected=!0);return c};v.ic=function(a,b){for(var c=0;c<b.length;c++)this.Fd(a,b[c])};v.lb=function(){for(var a=J(ta);0!=a.options.length;)a.remove(0);this.cb=[];this.Fd(a,new xd("Select profile...")).disabled="disabled";this.ic(a,this.va);this.ic(a,this.ib);this.ic(a,this.Ua)};
v.hg=function(){for(var a=[],b=0;b<this.va.length;b++)a[a.length]=this.va[b].encode();return a.join("&")};v.dg=function(a){if(""!=a){a=a.split("&");for(var b=0;b<a.length;b++)this.Rd(a[b])}};v.Rd=function(a){if(""==a)return null;a=a.split("=");for(var b=0;b<a.length;b++)a[b]=decodeURIComponent(a[b]);b=this.jg(a[0]);return null!=b?(a=b.decode(a),this.hc(a)):null};v.jg=function(a){for(var b=0;b<this.L.length;b++)if(this.L[b].encode()==a)return this.L[b];return null};
v.ff=function(){var a=J(ia).value;if(""==a)return T(2,"Comment should not be empty",!0),!1;if(1E6<a.length)return T(2,"Content length exceeds 1MB. Please abridge.",!0),!1;T(2,null,!1);return!0};v.Oc=function(){null!=this.s&&this.s.ab();this.Ta();var a=this.vb(!0);null!=a&&(this.G=a)};v.nh=function(){var a=this.vb(!1);null!=a&&this.Dd(a)};v.mh=function(){null!=this.s&&(this.s.ab(),this.s=null);this.lb();this.Oc()};
v.Je=function(){if(null==this.G||"NONE"==this.G.da())return T(1,"Please choose a profile",!0),!1;if(null!=this.s)return!1;J("encodedIds").value=this.hg();J(la).value=this.G.encode();return!0};v.ph=function(){this.G&&(this.Ta(),this.s.Xb())};v.wh=function(){this.ff()&&this.Je()&&this.Wd(!1)};v.xh=function(){this.ff()&&this.Je()&&this.Wd(!0)};v.Wd=function(a){a?J(Fa).value="true":J(Fa).value="false";this.Ta();a=J("commentForm");a.onsubmit();a.submit()};function $e(){xe(J(ea),"previewMode");return!0};var af;var bf=function(a,b,c){K.call(this);this.Kc=a;this.Pg=b||0;this.Ka=c;this.Vf=x(this.Vd,this)};z(bf,K);v=bf.prototype;v.R=0;v.m=function(){bf.u.m.call(this);this.stop();delete this.Kc;delete this.Ka};v.start=function(a){this.stop();this.R=nd(this.Vf,void 0!==a?a:this.Pg)};v.stop=function(){this.Lb()&&w.clearTimeout(this.R);this.R=0};v.fire=function(){this.stop();this.Vd()};v.Lb=function(){return 0!=this.R};v.Vd=function(){this.R=0;this.Kc&&this.Kc.call(this.Ka)};var ef=function(a,b,c,d,f,g){if(Bb&&f)return cf(a);if(f&&!d)return!1;if(!E){typeof b===za&&(b=df(b));var k=17==b||18==b||Bb&&91==b;if((!c||Bb)&&k||Bb&&16==b&&(d||g))return!1}if((F||Ab)&&d&&c)switch(a){case 220:case 219:case 221:case 192:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:return!1}if(D&&d&&b==a)return!1;switch(a){case 13:return E?g||f?!1:!(c&&d):!0;case 27:return!(F||Ab||E)}return E&&(d||f||g)?!1:cf(a)},cf=function(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=
a||(F||Ab)&&0==a)return!0;switch(a){case 32:case 43:case 63:case 64:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:case 163:case 58:return!0;case 173:return E;default:return!1}},df=function(a){if(E)a=ff(a);else if(Bb&&F)switch(a){case 93:a=91}return a},ff=function(a){switch(a){case 61:return 187;case 59:return 186;case 173:return 189;case 224:return 91;case 0:return 224;default:return a}};var gf=function(a,b,c,d){N.call(this,d);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=c};z(gf,N);var hf=function(a,b){P.call(this);a&&this.Hd(a,b)};z(hf,P);v=hf.prototype;v.Fa=null;v.Mb=null;v.Fc=null;v.Nb=null;v.I=-1;v.pa=-1;v.jc=!1;
var jf={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},kf={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},lf=Bb&&E;v=hf.prototype;
v.Ag=function(a){(F||Ab)&&(17==this.I&&!a.ctrlKey||18==this.I&&!a.altKey||Bb&&91==this.I&&!a.metaKey)&&this.Se();-1==this.I&&(a.ctrlKey&&17!=a.keyCode?this.I=17:a.altKey&&18!=a.keyCode?this.I=18:a.metaKey&&91!=a.keyCode&&(this.I=91));ef(a.keyCode,this.I,a.shiftKey,a.ctrlKey,a.altKey,a.metaKey)?(this.pa=df(a.keyCode),lf&&(this.jc=a.altKey)):this.handleEvent(a)};v.Se=function(){this.pa=this.I=-1};v.Bg=function(a){this.Se();this.jc=a.altKey};
v.handleEvent=function(a){var b=a.Ga,c=b.altKey;if(D&&a.type==ua){var d=this.pa;var f=13!=d&&27!=d?b.keyCode:0}else(F||Ab)&&a.type==ua?(d=this.pa,f=0<=b.charCode&&63232>b.charCode&&cf(d)?b.charCode:0):(a.type==ua?(lf&&(c=this.jc),b.keyCode==b.charCode?32>b.keyCode?(d=b.keyCode,f=0):(d=this.pa,f=b.charCode):(d=b.keyCode||this.pa,f=b.charCode||0)):(d=b.keyCode||this.pa,f=b.charCode||0),Bb&&63==f&&224==d&&(d=191));var g=d=df(d);d?63232<=d&&d in jf?g=jf[d]:25==d&&a.shiftKey&&(g=9):b.keyIdentifier&&b.keyIdentifier in
kf&&(g=kf[b.keyIdentifier]);if(!E||a.type!=ua||ef(g,this.I,a.shiftKey,a.ctrlKey,c,a.metaKey))a=g==this.I,this.I=g,b=new gf(g,f,a,b),b.altKey=c,this.dispatchEvent(b)};v.Ia=function(){return this.Fa};v.Hd=function(a,b){this.Nb&&this.detach();this.Fa=a;this.Mb=O(this.Fa,ua,this,b);this.Fc=O(this.Fa,"keydown",this.Ag,b,this);this.Nb=O(this.Fa,"keyup",this.Bg,b,this)};v.detach=function(){this.Mb&&(gd(this.Mb),gd(this.Fc),gd(this.Nb),this.Nb=this.Fc=this.Mb=null);this.Fa=null;this.pa=this.I=-1};
v.m=function(){hf.u.m.call(this);this.detach()};var mf={},nf=null,of=function(a){a=fb(a);delete mf[a];Rb(mf)&&nf&&nf.stop()},qf=function(){nf||(nf=new bf(function(){pf(Date.now())},20));var a=nf;a.Lb()||a.start()},pf=function(a){Lb(mf,function(b){b.kh(a)});Rb(mf)||qf()};var rf=function(){P.call(this);this.Aa=0;this.endTime=this.startTime=null};z(rf,P);v=rf.prototype;v.Oh=function(){this.Aa=1};v.Nh=function(){this.Aa=-1};v.Ye=function(){this.Aa=0};v.Ec=function(){return 1==this.Aa};v.re=function(){return-1==this.Aa};v.se=function(){return 0==this.Aa};v.lh=function(){this.V("begin")};v.Fe=function(){this.V("end")};v.rh=function(){this.V("finish")};v.uh=function(){this.V("pause")};v.vh=function(){this.V("play")};v.zh=function(){this.V("resume")};v.Ah=function(){this.V("stop")};
v.V=function(a){this.dispatchEvent(a)};var sf=function(a,b,c,d){rf.call(this);if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.pb=a;this.ig=b;this.duration=c;this.Cd=d;this.coords=[];this.progress=0};z(sf,rf);v=sf.prototype;
v.play=function(a){if(a||this.se())this.progress=0,this.coords=this.pb;else if(this.Ec())return!1;of(this);this.startTime=a=Date.now();this.re()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.progress||this.lh();this.vh();this.re()&&this.zh();this.Oh();var b=fb(this);b in mf||(mf[b]=this);qf();this.Qd(a);return!0};v.stop=function(a){of(this);this.Ye();a&&(this.progress=1);this.df(this.progress);this.Ah();this.Fe()};
v.pause=function(){this.Ec()&&(of(this),this.Nh(),this.uh())};v.m=function(){this.se()||this.stop(!1);this.oh();sf.u.m.call(this)};v.kh=function(a){this.Qd(a)};v.Qd=function(a){a<this.startTime&&(this.endTime=a+this.endTime-this.startTime,this.startTime=a);this.progress=(a-this.startTime)/(this.endTime-this.startTime);1<this.progress&&(this.progress=1);this.df(this.progress);1==this.progress?(this.Ye(),of(this),this.rh(),this.Fe()):this.Ec()&&this.gh()};
v.df=function(a){typeof this.Cd===p&&(a=this.Cd(a));this.coords=Array(this.pb.length);for(var b=0;b<this.pb.length;b++)this.coords[b]=(this.ig[b]-this.pb[b])*a+this.pb[b]};v.gh=function(){this.V("animate")};v.oh=function(){this.V("destroy")};v.V=function(a){this.dispatchEvent(new tf(a,this))};var tf=function(a,b){L.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.state=b.Aa};z(tf,L);var uf=function(a,b,c,d,f,g){function k(m){if(m){m.tabIndex=0;var n=h.Hh;n?m.setAttribute("role",n):m.removeAttribute("role");Yd(m,"goog-zippy-header");h.gg(m);h.fg(m)}}P.call(this);this.pc=f||Ec();this.ka=this.pc.Ia(a)||null;this.Za=this.pc.Ia(d||null);this.Pb=typeof b===p?b:null;this.Hh=g||"tab";this.Y=this.Pb||!b?null:this.pc.Ia(b);this.ba=1==c;void 0!==c||this.Pb||(this.Za?this.ba=this.Za.style.display!=q:this.ka&&(this.ba=Xd(this.ka,oa)));this.ze=new $d(this);this.Gc=new hf;this.Ee=new $d(this);
var h=this;k(this.ka);k(this.Za);this.nb(this.ba)};z(uf,P);v=uf.prototype;v.m=function(){uf.u.m.call(this);Nc(this.ze);Nc(this.Gc);Nc(this.Ee)};v.expand=function(){this.nb(!0)};v.collapse=function(){this.nb(!1)};v.toggle=function(){this.nb(!this.ba)};v.nb=function(a){this.Y?ce(this.Y,a):a&&this.Pb&&(this.Y=this.Pb());this.Y&&Yd(this.Y,"goog-zippy-content");this.Za?(ce(this.ka,!a),ce(this.Za,a)):this.nd(a);this.We(a);this.dispatchEvent(new vf("toggle",this,this.ba))};v.We=function(a){this.ba=a};
v.nd=function(a){if(this.ka){var b=this.ka;a?Yd(b,oa):Zd(b,oa);b=this.ka;a?Zd(b,na):Yd(b,na);b=this.ka;Array.isArray(a)&&(a=a.join(" "));""===a||void 0==a?(af||(af={atomic:!1,autocomplete:q,dropeffect:q,haspopup:!1,live:"off",multiline:!1,multiselectable:!1,orientation:"vertical",readonly:!1,relevant:"additions text",required:!1,sort:q,busy:!1,disabled:!1,hidden:!1,invalid:"false"}),a=af,"expanded"in a?b.setAttribute(fa,a.expanded):b.removeAttribute(fa)):b.setAttribute(fa,a)}};
v.fg=function(a){a&&(this.Gc.Hd(a),this.ze.Pa(this.Gc,"key",this.th))};v.gg=function(a){a&&this.Ee.Pa(a,"click",this.sh)};v.th=function(a){if(13==a.keyCode||32==a.keyCode)this.toggle(),this.Td(a),a.preventDefault(),a.stopPropagation()};v.sh=function(a){this.toggle();this.Td(a)};v.Td=function(a){this.dispatchEvent(new vf("action",this,this.ba,a))};var vf=function(a,b){L.call(this,a,b)};z(vf,L);var wf=function(a,b,c,d,f){d=d||Ec();var g=d.lc("DIV",{style:"overflow:hidden"});b=d.Ia(b);b.parentNode.replaceChild(g,b);g.appendChild(b);this.zb=g;this.O=null;uf.call(this,a,b,c,void 0,d,f);a=this.ba;this.zb.style.display=a?"":q;this.nd(a)};z(wf,uf);v=wf.prototype;v.animationDuration=500;v.Sf=function(a){return 1-Math.pow(1-a,3)};
v.nb=function(a){if(this.ba!=a||this.O){this.zb.style.display==q&&(this.zb.style.display="");var b=this.Y.offsetHeight;if(this.O){hd(this.O);this.O.stop(!1);var c=b-Math.abs(parseInt(this.Y.style.marginTop,10))}else c=a?0:b;this.nd(a);this.O=new sf([0,c],[0,a?b:0],this.animationDuration,this.Sf);O(this.O,["begin","animate","end"],this.hh,!1,this);O(this.O,"begin",x(this.ih,this,a));O(this.O,"end",x(this.jh,this,a));this.O.play(!1)}};
v.hh=function(a){var b=this.Y;b.style.marginTop=a.y-b.offsetHeight+"px"};v.ih=function(a){this.dispatchEvent(new vf("a",this,a))};v.jh=function(a){a&&(this.Y.style.marginTop="0");hd(this.O);this.We(a);this.O=null;a||(this.zb.style.display=q);this.dispatchEvent(new vf("toggle",this,a));this.dispatchEvent(new vf("b",this,a))};var xf=null;var V=new Ze;y("BLOG_CMT_LoggedInGaiaIdentity",Se);y("BLOG_CMT_NotLoggedInGaiaIdentityFactory",Ve);y("BLOG_CMT_NameUrlIdentityFactory",Ye);y("BLOG_CMT_AnonymousIdentityFactory",Bd);y("BLOG_CMT_onPost",function(){$e();return V.wh()});y("BLOG_CMT_onPreview",function(){return V.xh()});y("BLOG_CMT_onCommentBodyChange",function(){});y("BLOG_CMT_onCancel",function(){return V.mh()});y("BLOG_CMT_onSelectorChange",function(){return V.Oc()});y("BLOG_CMT_onContinue",function(){return V.nh()});
y("BLOG_CMT_onEdit",function(){return V.ph()});y("BLOG_CMT_addIdentity",function(a){return V.hc(a)});y("BLOG_CMT_addAndSelectIdentity",function(a){return V.Dd(a)});y("BLOG_CMT_addIdentityFactory",function(a){return V.Ed(a)});y("BLOG_CMT_addNameUrlIdentityFactory",function(){return V.Pf()});y("BLOG_CMT_addAnonIdentity",function(){return V.Of()});y("BLOG_CMT_addNotLoggedInGaiaIdentity",function(){return V.Qf()});
y("BLOG_CMT_init",function(a,b){oe(document.location.href);V.Gh();V.Oc();V.Be();Qe(a,b);"true"==J(Fa).value&&(J(Fa).value="false",ve(J(ea),"previewMode"));ne();return!0});y("BLOG_CMT_createPhotoZippy",function(a,b){J(a)&&J(b)&&(xf=new wf(a,b))});y("BLOG_CMT_closePhotoZippy",function(){null!=xf&&xf.collapse()});y("BLOG_CMT_finalizeBG",function(){window.Jd&&window.Jd.invoke(function(a){document.getElementById(ha).value=a})});
y("BLOG_CMT_getBG",function(){var a=new Hd("/comment-iframe-bg.g"),b=document.getElementById(ha).value;b&&a.Wb(ha,b);b=null;"Microsoft Internet Explorer"==window.navigator.appName&&(document.documentMode?b=document.documentMode:(b=5,document.compatMode&&"CSS1Compat"==document.compatMode&&(b=7)));b&&a.Wb("iemode",b);document.getElementById("pageID")&&a.Wb("page","1");Rd&&a.Wb("bgint",Rd);td(a,function(){if(this.gb()){var c=eval(this.rg());c instanceof Object&&c.length&&(1<c.length&&(eval(c[1]),Rd=
c[2]),window.Jd=new botguard.bg(c[0]))}})});y("BLOG_CMT_setBG",function(a){Rd=a});y("BLOG_CMT_subscription.toggle",function(){if(!Ne){Ne=!0;var a=J("commentSubscriptionForm");td(a.action,function(){Ne=!1;if(this.gb()){var b=this.he();null!=b.errorMessage?T(3,b.errorMessage,!0):se(b.statusMessage);Qe(b.can_subscribe,b.is_subscribed)}else T(3,"An error occurred while contacting the server.",!0)},"POST",Me(a))}});y("BLOG_CMT_showStatusMessage",se);
y("BLOG_CMT_showPostErrorMessage",function(a){T(4,a,!0)});y("BLOG_CMT_hidePreview",function(){$e();V.lb();me()});y("BLOG_xhr",Q);Q.send=td;Q.prototype.isSuccess=Q.prototype.gb;Q.prototype.getResponseJson=Q.prototype.he;y("$",J);function yf(a,b,c){var d=a.ownerDocument;b=b._GetHelper();var f=b._GetData(),g=c._GetAllData();a=zf(d,a,l,"widget-wrap1");a=zf(d,a,l,"widget-wrap2");a=zf(d,a,l,"widget-wrap3");var k=zf(d,a,l,"widget-content");if(a=f.version&&1<f.version)k.className+=" visibility",zf(d,k,l,"layout-widget-state "+(f.isVisible?"visible":"not-visible")).setAttribute("title",f.visibilityTooltipMessage);var h=zf(d,k,l,"layout-title");if(f[wa]){var m=zf(d,k,l,va);m.appendChild(d.createTextNode(f[wa]));m.setAttribute("title",
f[va])}h.appendChild(d.createTextNode(f["layout-title"]));f=zf(d,k,"a","editlink");var n=b._GenerateWidgetMetadata();f.target="chooseWidget";f.onclick=function(){return c._PopupConfig(d.getElementById(n.instanceId))};a&&(f.className+=" icon");f.appendChild(d.createTextNode(g.messages.edit||"Edit"))}function zf(a,b,c,d){a=a.createElement(c);a.className=d;b.appendChild(a);return a};var Af=function(){this.Ch={};this.De={};this.Rc={};this.ef=null;this.Me=[]};ab(Af);Af.prototype.ce=function(a,b){return a+"_"+b+".js"};var Bf=function(a){eval(a)};Af.prototype.ne=function(a,b){y("__gjsload__",Bf);this.ef=a.replace(/\.js$/,"");b&&(this.ce=b);this.Me.forEach(function(c){this.Xg(c)},this);rb(this.Me)};Af.prototype.Eh=function(a,b,c){var d=this.De,f=this.Ch;d[a]||(d[a]={});if(c)d[a][b]=c;else if(f[a]){for(b=0;b<f[a].length;++b)(0,f[a][b][1])(d[a][f[a][b][0]]);delete f[a];delete this.Rc[a]}};
Af.prototype.Xg=function(a){nd(function(){if(!this.De[a]){var b=this.ce(this.ef,a),c=Qb(this.Rc,b);this.Rc[a]=b;if(!c){c=Jc("SCRIPT",{type:"text/javascript"});qe();var d=Vb();b=d?d.createScriptURL(b):b;b=new $b(b,Zb);c.src=b instanceof $b&&b.constructor===$b?b.Xc:"type_error:TrustedResourceUrl";(b=yc("script[nonce]",c.ownerDocument&&c.ownerDocument.defaultView))&&c.setAttribute("nonce",b);document.body.appendChild(c)}}},0,this)};var Cf=function(){this.P=[];this.U=[]};v=Cf.prototype;v.Zg=function(){0===this.P.length&&(this.P=this.U,this.P.reverse(),this.U=[])};v.enqueue=function(a){this.U.push(a)};v.dequeue=function(){this.Zg();return this.P.pop()};v.o=function(){return this.P.length+this.U.length};v.isEmpty=function(){return 0===this.P.length&&0===this.U.length};v.clear=function(){this.P=[];this.U=[]};v.contains=function(a){return A(this.P,a)||A(this.U,a)};
v.remove=function(a){var b=this.P;var c=ob(b,a);0<=c?(Array.prototype.splice.call(b,c,1),b=!0):b=!1;return b||sb(this.U,a)};v.F=function(){for(var a=[],b=this.P.length-1;0<=b;--b)a.push(this.P[b]);var c=this.U.length;for(b=0;b<c;++b)a.push(this.U[b]);return a};var Df=function(a){this.i=new He;this.size=0;a&&this.addAll(a)},Ef=function(a){var b=typeof a;return b==r&&a||b==p?"o"+fb(a):b.substr(0,1)+a};v=Df.prototype;v.o=function(){return this.i.size};v.add=function(a){this.i.set(Ef(a),a);this.ga(this.i.size)};v.addAll=function(a){a=Dd(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c]);this.ga(this.i.size)};v.Ub=function(a){a=Dd(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c]);this.ga(this.i.size)};
v.delete=function(a){a=this.i.remove(Ef(a));this.ga(this.i.size);return a};v.remove=function(a){return this.delete(a)};v.clear=function(){this.i.clear();this.ga(0)};v.isEmpty=function(){return 0===this.i.size};v.has=function(a){return this.i.Da(Ef(a))};v.contains=function(a){return this.i.Da(Ef(a))};v.F=function(){return this.i.F()};v.values=function(){return this.i.values()};v.clone=function(){return new Df(this)};v.equals=function(a){return this.o()==Cd(a)&&this.Tg(a)};
v.Tg=function(a){var b=Cd(a);if(this.o()>b)return!1;!(a instanceof Df)&&5<b&&(a=new Df(a));return Gd(this,function(c){var d=a;return d.contains&&typeof d.contains==p?d.contains(c):d.Wa&&typeof d.Wa==p?d.Wa(c):bb(d)||typeof d===u?A(d,c):Qb(d,c)})};v.ia=function(){return this.i.ia(!1)};Df.prototype[Symbol.iterator]=function(){return this.values()};Df.prototype.ga=function(a){this.size=a};var Ff=function(a,b){K.call(this);this.Ce=a||0;this.Rb=b||10;if(this.Ce>this.Rb)throw Error("[goog.structs.Pool] Min can not be greater than max");this.ca=new Cf;this.oa=new Df;this.delay=0;this.Hc=null;this.ub()};z(Ff,K);v=Ff.prototype;v.Cb=function(){var a=Date.now();if(!(null!=this.Hc&&a-this.Hc<this.delay)){var b=this.Fh();b&&(this.Hc=a,this.oa.add(b));return b}};v.Zc=function(a){return this.oa.remove(a)?(this.fc(a),!0):!1};
v.Fh=function(){for(var a;0<this.be()&&(a=this.ca.dequeue(),!this.Nc(a));)this.ub();!a&&this.o()<this.Rb&&(a=this.mc());return a};v.fc=function(a){this.oa.remove(a);this.Nc(a)&&this.o()<this.Rb?this.ca.enqueue(a):this.oc(a)};v.ub=function(){for(var a=this.ca;this.o()<this.Ce;)a.enqueue(this.mc());for(;this.o()>this.Rb&&0<this.be();)this.oc(a.dequeue())};v.mc=function(){return{}};v.oc=function(a){if(typeof a.ra==p)a.ra();else for(var b in a)a[b]=null};
v.Nc=function(a){return typeof a.Wf==p?a.Wf():!0};v.contains=function(a){return this.ca.contains(a)||this.oa.contains(a)};v.o=function(){return this.ca.o()+this.oa.o()};v.lg=function(){return this.oa.o()};v.be=function(){return this.ca.o()};v.isEmpty=function(){return this.ca.isEmpty()&&this.oa.isEmpty()};v.m=function(){Ff.u.m.call(this);if(0<this.lg())throw Error("[goog.structs.Pool] Objects not released");delete this.oa;for(var a=this.ca;!a.isEmpty();)this.oc(a.dequeue());delete this.ca};var Gf=function(a,b){this.ye=a;this.$b=b};Gf.prototype.getKey=function(){return this.ye};Gf.prototype.clone=function(){return new Gf(this.ye,this.$b)};var Hf=function(a){this.M=[];a&&this.Mg(a)};v=Hf.prototype;v.pe=function(a,b){var c=this.M;c.push(new Gf(a,b));this.eh(c.length-1)};v.Mg=function(a){if(a instanceof Hf){var b=a.ma();a=a.F();if(0>=this.o()){for(var c=this.M,d=0;d<b.length;d++)c.push(new Gf(b[d],a[d]));return}}else b=Pb(a),a=Ob(a);for(d=0;d<b.length;d++)this.pe(b[d],a[d])};v.remove=function(){var a=this.M,b=a.length,c=a[0];if(!(0>=b))return 1==b?rb(a):(a[0]=a.pop(),this.ah(0)),c.$b};
v.ah=function(a){for(var b=this.M,c=b.length,d=b[a];a<c>>1;){var f=this.pg(a),g=this.sg(a);f=g<c&&b[g].getKey()<b[f].getKey()?g:f;if(b[f].getKey()>d.getKey())break;b[a]=b[f];a=f}b[a]=d};v.eh=function(a){for(var b=this.M,c=b[a];0<a;){var d=this.qg(a);if(b[d].getKey()>c.getKey())b[a]=b[d],a=d;else break}b[a]=c};v.pg=function(a){return 2*a+1};v.sg=function(a){return 2*a+2};v.qg=function(a){return a-1>>1};v.F=function(){for(var a=this.M,b=[],c=a.length,d=0;d<c;d++)b.push(a[d].$b);return b};
v.ma=function(){for(var a=this.M,b=[],c=a.length,d=0;d<c;d++)b.push(a[d].getKey());return b};v.Wa=function(a){return qb(this.M,function(b){return b.$b==a})};v.Da=function(a){return qb(this.M,function(b){return b.getKey()==a})};v.clone=function(){return new Hf(this)};v.o=function(){return this.M.length};v.isEmpty=function(){return 0===this.M.length};v.clear=function(){rb(this.M)};var If=function(){Hf.call(this)};z(If,Hf);If.prototype.enqueue=function(a,b){this.pe(a,b)};If.prototype.dequeue=function(){return this.remove()};var Jf=function(a,b){this.Sd=void 0;this.Vb=new If;Ff.call(this,a,b)};z(Jf,Ff);v=Jf.prototype;v.Cb=function(a,b){if(!a)return(a=Jf.u.Cb.call(this))&&this.delay&&(this.Sd=w.setTimeout(x(this.Eb,this),this.delay)),a;this.Vb.enqueue(void 0!==b?b:100,a);this.Eb()};v.Eb=function(){for(var a=this.Vb;0<a.o();){var b=this.Cb();if(b)a.dequeue().apply(this,[b]);else break}};v.fc=function(a){Jf.u.fc.call(this,a);this.Eb()};v.ub=function(){Jf.u.ub.call(this);this.Eb()};
v.m=function(){Jf.u.m.call(this);w.clearTimeout(this.Sd);this.Vb.clear();this.Vb=null};var Kf=function(a,b,c,d){this.wc=a;this.ha=!!d;Jf.call(this,b,c)};z(Kf,Jf);Kf.prototype.mc=function(){var a=new Q,b=this.wc;b&&b.forEach(function(c,d){a.headers.set(d,c)});this.ha&&a.jd(!0);return a};Kf.prototype.Nc=function(a){return!a.Ea&&!a.Lb()};var Lf=function(a,b,c,d,f,g){P.call(this);this.Mc=void 0!==a?a:1;this.Ba=void 0!==f?Math.max(0,f):0;this.ha=!!g;this.Sa=new Kf(b,c,d,g);this.T=new He;this.Ab=new $d(this)};z(Lf,P);var Mf=[Ba,e,Ia,"error","abort","timeout"];v=Lf.prototype;v.gd=function(a){this.Ba=Math.max(0,a)};
v.send=function(a,b,c,d,f,g,k,h,m,n){if(this.T.get(a))throw Error("[goog.net.XhrManager] ID in use");b=new Nf(b,x(this.zg,this,a),c,d,f,k,void 0!==h?h:this.Mc,m,void 0!==n?n:this.ha);this.T.set(a,b);a=x(this.wg,this,a);this.Sa.Cb(a,g);return b};v.abort=function(a,b){var c=this.T.get(a);if(c){var d=c.ac;c.Jh(!0);b&&(d&&(this.Qe(d,c.rd),Zc(d,Ba,function(){this.Sa.Zc(d)},!1,this)),this.T.remove(a));d&&d.abort()}};
v.wg=function(a,b){var c=this.T.get(a);c&&!c.ac?(this.Rf(b,c.rd),b.gd(this.Ba),b.Mh(c.Ra),b.jd(c.ha),c.ac=b,this.dispatchEvent(new Of(Ba,this,a,b)),this.Te(a,b),c.Bd&&b.abort()):this.Sa.Zc(b)};v.zg=function(a,b){var c=b.target;switch(b.type){case Ba:this.Te(a,c);break;case e:return this.xg(a,c,b);case Ia:this.Cg(a,c);break;case "timeout":case "error":this.yg(a,c);break;case "abort":this.vg(a,c)}return null};
v.Te=function(a,b){var c=this.T.get(a);!c||c.Od||c.vc()?(c&&(this.Qe(b,c.rd),this.T.remove(a)),this.Sa.Zc(b)):(c.Lg(),b.send(c.getUrl(),c.$g,c.getContent(),c.wc))};v.xg=function(a,b,c){var d=this.T.get(a);if(7==b.Oa||b.gb()||d.vc())if(this.dispatchEvent(new Of(e,this,a,b)),d&&(d.Kh(!0),d.Nd))return d.Nd.call(b,c);return null};v.vg=function(a,b){this.dispatchEvent(new Of("abort",this,a,b))};v.Cg=function(a,b){this.dispatchEvent(new Of(Ia,this,a,b))};
v.yg=function(a,b){this.T.get(a).vc()&&this.dispatchEvent(new Of("error",this,a,b))};v.Qe=function(a,b,c){this.Ab.Zb(a,c||Mf,b)};v.Rf=function(a,b,c){this.Ab.Pa(a,c||Mf,b)};v.m=function(){Lf.u.m.call(this);this.Sa.ra();this.Sa=null;this.Ab.ra();this.Ab=null;this.T.clear();this.T=null};var Of=function(a,b,c,d){L.call(this,a,b);this.id=c;this.ac=d};z(Of,L);
var Nf=function(a,b,c,d,f,g,k,h,m){this.Sh=a;this.$g=c||"GET";this.$f=d;this.wc=f||null;this.Mc=void 0!==k?k:1;this.Id=0;this.Bd=this.Od=!1;this.rd=b;this.Nd=g;this.Ra=h||"";this.ha=!!m;this.ac=null};v=Nf.prototype;v.getUrl=function(){return this.Sh};v.getContent=function(){return this.$f};v.Lg=function(){this.Id++};v.vc=function(){return this.Id>this.Mc};v.Kh=function(a){this.Od=a};v.Jh=function(a){this.Bd=a};function Pf(a,b,c,d,f){this.Jb=a;this.Ue=b;this.rootElement=c||null;this.data=d||null;if(f){if(this.nc=f,"displayModeSnippet"!=f&&"displayModeFull"!=f&&f!=ja&&f!=ka)throw"bad display mode: "+f;}else this.nc=ka;this.Dc=!1}Pf.prototype.ng=function(){return this.Jb};function Qf(a){this.eg=!0;this.K=a;this.qd=null}v=Qf.prototype;v.If=function(a){this.qd=a};v.pf=function(){return this.K.data};v.Df=function(a){return this.K.data=a};v.Ff=function(a){return this.K.Dc=a};
v.mf=function(){var a={};a.type=this.qd.Rh;a.instanceId=this.K.Jb;a.sectionId=this.K.Ue;a.actionUrl=X.Uf;a.quickEditUrl=X.Xd+"&widgetType="+this.qd.Rh+"&widgetId="+this.K.Jb+"&sectionId="+this.K.Ue+"&action="+X.lf;return a};function X(){}X.sf=function(a,b){X.Ca={};X.Xd=a;X.Uf=b;X.tc={};X.gf=new Lf;X.Sc=0;O(X.gf,Ba,function(){X.Sc++});O(X.gf,e,function(){X.Sc--})};X.Gf=function(a,b){X.Le=a;X.Ke=b};X.Kf=function(a){a=X.kf(a.document);document.body.appendChild(a)};
X.Jf=function(a){X.Kf(window);if(window.parent==window){var b="Preview";a&&(b=a);a=X.jf(window.document,b);document.body.appendChild(a[0]);document.body.appendChild(a[1])}};X.lf="editWidget";X.Hf=function(a){X.Th=a};X.qf=function(){return X.Th};X.Ef=function(a){X.tc=a};X.nf=function(){var a={},b;for(b in X.tc){var c=X.tc[b];a[c.name]=c.data}c={};for(b in X.Ca)c[b]=X.Ca[b].ua.K.data;a.widgets=c;return a};X.xd=function(a,b){var c=new Qf(b);a=new window[a](c);c.If(a);X.Ca[b.Jb]=a;X.ud(a);return a};
X.Af=function(a,b){a=X.xd(a,b);a.ua.Ff(!0);return a};X.ud=function(a){a.ua.K.nc!=ka&&(a.ua.eg=!1)};X.dc=function(a){return X.Ca?X.Ca[a]:null};X.yf=function(a,b,c,d,f){var g="";d&&(g="&widgetId="+d);a=X.Xd+"&action="+a+"&sectionId="+b+"&widgetType="+c+g;if(window.name==f)return window.location.replace(a),window.focus(),window;f=window.open(a,f,"width=570,height=600,left=75,top=20,resizable=yes,scrollbars=yes");f.focus();return f};
X.xf=function(a){var b=a.getAttribute("id"),c=a.parentNode.getAttribute("id");a=a.getAttribute("widgetType");X.Ke&&X.Ke(c,a,b);return!1};X.zf=function(a){a=a.parentNode.getAttribute("id");X.Le&&X.Le(a);return!1};X.sd=function(a,b){0==X.Sc?a.setTimeout(function(){a.close()},b):a.setTimeout(function(){X.sd(a,b)},200)};X.uf=function(a,b){a&&(X.sd(a,100),X.Lf(a,b))};
X.Lf=function(a,b){if(a){var c=a.document.getElementById(Ga);c&&(c=c.innerHTML);c&&a&&a.opener.parent&&a.opener.parent.editor&&a.opener.parent.editor.SetSaveMessage(c,b)}};X.vd=function(a,b,c){a=X.Ca[a];if(null!=c.errors){var d=window;X.yd(d,c.errors);a&&a.tb?a.tb(b,c,d):X.tb(c,d)}else a.vd(b,c)};X.tb=function(a,b){a=a["error-details"];for(var c in a)Rf(c,a[c],b.document)};X.vf=function(a,b){window.parent&&window.parent.editor&&b?X.wd(a,b):window.location.replace(window.location.href)};
X.wd=function(a,b){var c=X.dc(a);c.ua.Df(b.data);a=document.getElementById(a);Mc(a);yf(a,c,X)};X.rf=function(a,b,c){null!=c.errors&&(X.yd(window,c.errors),X.tb(c,window))};X.wf=function(a){var b=X.dc(a);b&&(b.ua.K.nc==ja?top.editor.HandleDeleteWidget(b.ua.K.rootElement):(b=b.ua.K.rootElement,b.parentNode.removeChild(b)),delete X.Ca[a])};X.tf=function(a){var b=!1;try{if(a.opener){var c="X"+a.opener.document.domain;c&&"X"!=c&&(b=!0)}}catch(d){}return b};X.Bf="status-msg-yellow-on-white";
X.yd=function(a,b){a||(a=self);var c=a.document.getElementById(Ga);c&&Sd(c,re(b));(a=a.document.getElementById("status-message"))&&ve(a,X.Bf)};
X.kf=function(a){a=a.createElement(l);a.className="blogger-clickTrap singleton-element";a.style.position="fixed";a.style.top="0";a.style.left="0";a.style.width="100%";a.style.height="100%";D&&!Jb(7)&&(a.style.height="expression(this.parentNode.clientHeight)");a.style.zIndex="1000";a.style.cursor="default";a.onclick=X.ec;a.onmousedown=X.ec;a.onmouseup=X.ec;a.style.background="white";a.style.filter="alpha(opacity=1)";a.style.opacity=".01";a.textContent="\u00a0";return a};
X.jf=function(a,b){var c=X.td(a,b);a=X.td(a,b);c.style.backgroundColor="#000";c.style.border="1px solid #aaa";D&&(c.style.filter=' progid:DXImageTransform.Microsoft.Matrix(sizingMethod="auto expand", M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678) alpha(opacity=50)');c.style.opacity=".5";a.style.border="1px solid transparent";c.style.zIndex=1200;a.style.zIndex=1200;return[c,a]};
X.td=function(a,b){a=a.createElement(l);a.style.position="absolute";a.style.top="75px";a.style.left="-225px";a.style.width="600px";a.style.height="28px";a.style.margin="0";a.style.padding="10px";a.style.fontSize="24px";a.style.textAlign="center";a.style.color="#fff";a.style.fontFamily='"trebuchet ms",verdana,arial,sans-serif';D&&(a.style.top="-140px",a.style.left="-140px",a.style.filter=' progid:DXImageTransform.Microsoft.Matrix(sizingMethod="auto expand", M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678)');
a.style.MozTransform=Ca;a.style.MozTransformOrigin="50% 0";a.style.WebkitTransform=Ca;a.style.WebkitTransformOrigin="50% 0";Sd(a,re(b));a.className="singleton-element";return a};X.ec=function(a){a||(a=window.event);a&&(a.cancelBubble=!0,a.stopPropagation&&a.stopPropagation());return!1};var Sf=function(a,b){b||(b=document);return b.getElementById("errormessage_"+a)},Tf=function(a){if(a=Sf(a))Mc(a),a.className="errorbox-good"},Rf=function(a,b,c){if(a=Sf(a,c))Sd(a,re(b)),a.className="errorbox-bad errormsg"};
y("_WidgetManager",X);X._SetOpenWidgetDialogs=X.Gf;X._Init=X.sf;X._SetWidgetRefreshUrl=X.Hf;X._GetWidgetRefreshUrl=X.qf;X._DisplayWidget=X.ud;X._GetWidget=X.dc;X._HandleControllerResult=X.vd;X._HandlePageActionResult=X.rf;X._IsOpenerReachable=X.tf;X._SetDataContext=X.Ef;X._SetupPreview=X.Jf;X._RegisterWidget=X.xd;X._RegisterNewWidget=X.Af;X._PopupPaneFromParams=X.yf;X._PopupConfig=X.xf;X._PopupToolbox=X.zf;X._KillPopupDelay=X.uf;X._OnWidgetConfigured=X.vf;X._OnWidgetConfiguredWithData=X.wd;
X._OnWidgetDeleted=X.wf;y("_WidgetInfo",Pf);Pf.prototype._getInstanceId=Pf.prototype.ng;Qf.prototype._GetData=Qf.prototype.pf;Qf.prototype._GenerateWidgetMetadata=Qf.prototype.mf;X._GetAllData=X.nf;y("widget_module_provide",function(a,b,c){Af.mg().Eh(a,b,c)});var Y=function(a,b,c,d,f,g,k,h){this.H=a;this.Kd="null"!=b?b:null;this.we=c;this.ue=d;this.ve=f;this.Ve=g;this.xe=k;this.Ih=h;this.Hb=this.La=-1;this.yc=null;this.jb=300;this.Lc="200px";this.N=document.getElementById(this.H+"_picImg");this.xb=document.getElementById(this.H+"_changeImageLink");this.Gb=document.getElementById(this.H+"_imageChoiceTable");this.zc=document.getElementById(this.H+"_imgSrcFromPCRadio");this.me=document.getElementById(this.H+"_imgSrcFromWebRadio");this.j=document.getElementById(this.H+
"_imgFileNameInput");this.bb=document.getElementById(this.H+"_imgUrlTextInput");this.Gd=window.frames[this.H+"_asynchronousFileUploadIframe"];this.xc=0;this.B=new Image;this.B.onload=x(this.Bh,this);this.B.onerror=x(this.qh,this);this.Zd=!1;this.Ha=this.D=this.Ob=null;this.Yc=!1};v=Y.prototype;
v.Bh=function(){this.xc=0;Tf(this.H+da);Tf(this.H+ca);this.zc.checked&&0!=this.La||(this.La=this.B.width,this.Hb=this.B.height,this.yc=this.B.src);var a=1,b=1;this.B.width>this.jb&&(a=this.jb/this.B.width);this.B.height>this.jb&&(b=this.jb/this.B.height);a=Math.min(a,b);this.N.style.width=Math.round(this.B.width*a)+"px";this.N.style.height=Math.round(this.B.height*a)+"px";this.N.src=this.B.src;this.N.style.display="";this.Gb.style.display=q;this.xb.style.display="";this.j.disabled=!0;this.we&&this.we.call({},
this.N.src,this.yc,this.La,this.Hb)};v.ob=function(a,b,c,d){a?(Rf(this.H+ca,b),Tf(this.H+da)):(Rf(this.H+da,b),Tf(this.H+ca));this.N.style.display=q;this.Gb.style.display="";this.xb.style.display=q;this.j.disabled=!1;this.ue&&this.ue.call({},c,d)};v.qh=function(){if(2>this.xc){this.xc++;var a=this.B.src;this.B.src="";this.hb(a)}else this.ob(this.zc.checked,WidgetMessages.SIV_INVALID_URL,this.N.src,[])};v.hb=function(a){this.$e();this.B.src=a};
v.Xf=function(a){a=a||window.event;window.event?(a.returnValue=!1,a.cancelBubble=!0):(a.preventDefault(),a.stopPropagation());this.N.style.display=q;this.xb.style.display=q;this.Gb.style.display="";this.j.disabled=!1;this.bb.value="";this.Re();this.Yc=!0;this.ve&&this.ve.call({})};v.Jg=function(){this.zc.checked="true";this.bb.value="";this.$e();this.dh();this.Zd=!0;try{this.D.submit()}catch(a){this.ob(!0,WidgetMessages.SIV_INVALID_URL,this.D.value,[])}this.bh()};
v.kc=function(){var a=this.Gd.document.result;if(a)if(a.hasErrors)0<a.errors.length?this.ob(!0,a.errors[0].message,this.j.value,a.errors):this.ob(!0,WidgetMessages.SIV_INVALID_URL,this.j.value,a.errors);else{var b=Math.max(a.origWidth,a.origHeight),c=this.je();0!=this.La&&-1!=c&&b>c?(b=c/b,this.La=Math.round(a.origWidth*b),this.Hb=Math.round(a.origHeight*b)):(this.La=a.origWidth,this.Hb=a.origHeight);this.yc=a.mainSrc;this.hb(a.thumbSrc)}else this.ob(!0,WidgetMessages.SIV_INVALID_URL,this.j.value,
[])};v.Kg=function(a){9!=(a||window.event).keyCode&&(this.me.checked="true",null!=this.Ob&&(window.clearTimeout(this.Ob),this.Ob=null),a=x(this.Ug,this),this.Ob=window.setTimeout(a,1E3))};v.Ug=function(){if(this.Yc||this.B.src!=this.bb.value)this.Re(),this.hb(this.bb.value);this.Yc=!1};v.Wg=function(a){this.me.checked=!0;this.bb.value=a;this.hb(a)};
v.$e=function(){this.N.src="https://resources.blogblog.com/img/icon_inprogress.gif";this.N.style.width=this.Lc;this.N.style.height=this.Lc;this.N.style.display="";this.Gb.style.display=q;this.xb.style.display=q};
v.dh=function(){if(!this.D){this.D=document.createElement("form");this.D.action="imageUpload.do";this.D.method="POST";this.D.target=this.Gd.name;this.D.encoding="multipart/form-data";this.D.style.display=q;if(this.Kd){var a=Kc(document,aa);a.type=qa;a.name="blogID";a.value=this.Kd;this.D.appendChild(a)}a=Kc(document,aa);a.type=qa;a.name=Da;a.id=Da;this.D.appendChild(a);a=Kc(document,aa);a.type=qa;a.name="security_token";a.value=this.Ih;this.D.appendChild(a);document.body.appendChild(this.D)}a=this.je();
-1==a&&(a=1600);document.getElementById(Da).value=a;this.Ha={parent:this.j.parentNode,nextSibling:this.j.nextSibling};this.j.parentNode.removeChild(this.j);this.D.appendChild(this.j)};v.Lh=function(a){this.jb=a;this.Lc=a+"px"};v.bh=function(){this.D.removeChild(this.j);this.Ha&&this.Ha.nextSibling?this.Ha.parent.insertBefore(this.j,this.Ha.nextSibling):this.Ha.parent.appendChild(this.j)};
v.Re=function(){var a=Kc(document,aa);a.type="file";a.name=this.j.name;a.id=this.j.id;a.onchange=this.j.onchange;var b=this.j.nextSibling;null==b?this.j.parentNode.appendChild(a):this.j.parentNode.insertBefore(a,b);this.j.parentNode.removeChild(this.j);this.j=a};v.je=function(){return-1==this.Ve&&this.xe?this.xe():this.Ve};var Z=function(){this.pd={}};Z.prototype.ag=function(a,b,c,d,f,g,k,h){this.pd[a]=new Y(a,b,eval(c),eval(d),eval(f),g,eval(k),h);return this.pd[a]};Z.prototype.ie=function(a){return this.pd[a]};
Z.prototype.kc=function(a){(a=this.ie(a))&&a.Zd&&a.kc()};y("_UploadSimpleImage",new Z);Z.prototype._createUsiContainer=Z.prototype.ag;Z.prototype._getUsiContainer=Z.prototype.ie;Z.prototype._channelResultArrived=Z.prototype.kc;Y.prototype._changeImage=Y.prototype.Xf;Y.prototype._imgUrlFileOnChange=Y.prototype.Jg;Y.prototype._imgUrlTextOnKeyUp=Y.prototype.Kg;Y.prototype._loadInitialUrl=Y.prototype.Wg;Y.prototype._loadImageFromUrl=Y.prototype.hb;Y.prototype._setPreviewSize=Y.prototype.Lh;}).call(this);
