(part "EP5357HUI"
    (packageRef "QFN40P225X250X120-16N-D")
    (interface
        (port "1" (symbPinId 1) (portName "NC(SW)_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "PGND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "LLM") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NC") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VSENSE") (portType INOUT))
        (port "6" (symbPinId 6) (portName "AGND") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VOUT_1") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VOUT_2") (portType INOUT))
        (port "9" (symbPinId 9) (portName "VS2") (portType INOUT))
        (port "10" (symbPinId 10) (portName "VS1") (portType INOUT))
        (port "11" (symbPinId 11) (portName "VS0") (portType INOUT))
        (port "12" (symbPinId 12) (portName "ENABLE") (portType INOUT))
        (port "13" (symbPinId 13) (portName "AVIN") (portType INOUT))
        (port "14" (symbPinId 14) (portName "PVIN") (portType INOUT))
        (port "15" (symbPinId 15) (portName "NC(SW)_2") (portType INOUT))
        (port "16" (symbPinId 16) (portName "NC(SW)_3") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "884-EP5357HUI")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Intel-Altera/EP5357HUI?qs=Bt1661OnjFKQMLj2uHL8Lg%3D%3D")
    (property "Manufacturer_Name" "Intel")
    (property "Manufacturer_Part_Number" "EP5357HUI")
    (property "Description" "Switching Voltage Regulators 600mA/5MHz Buck Reg Int Inductor, Hi VID")
    (property "Datasheet_Link" "https://www.intel.com/content/dam/www/programmable/us/en/pdfs/literature/ds/ep5357_03409.pdf")
    (property "symbolName1" "EP5357HUI")
)
